In [1]:
from sentence_transformers import SentenceTransformer
import torch
# Load embedding model
device = "cuda" if torch.cuda.is_available() else "cpu"
model = SentenceTransformer("google/embeddinggemma-300m", device=device)

def create_embedding(texts):
    if type(texts) == list: # the input param is a list contains text chunks
        embeddings = model.encode(texts)
        return embeddings
    elif type(texts) == str: # just one text chunk
        embedding = model.encode([texts])
        return embedding
    else:
        raise ValueError("The texts paramters should be str or list[str]")

print(device)

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

cuda

In [2]:
import os
dir_path = os.getcwd()
print("The directory of this script is:", dir_path)
root_path = os.path.dirname(dir_path)
print("The root directory is:", root_path)

The directory of this script is: d:\Documents\GitHub\NodeRAG\testing
The root directory is: d:\Documents\GitHub\NodeRAG

In [3]:
#LLM api call
from google import genai
with open(f"{root_path}/API_KEY.txt", "r", encoding="utf-8") as f:
    API_KEY = f.read()

def call_gemini(text):
    client = genai.Client(api_key = API_KEY)
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=text
    )
    return response.text, response.usage_metadata.total_token_count

In [4]:
import sys
import numpy as np
sys.path.append(root_path)
from testing.metrics.faithfulness import compute_faithfulness #Detect hallucinations: Measures how much the LLM answer is based on the retrieved context
"""
question: str,
answer: str,
contexts: List[str],
call_gemini,
max_retries: int = 5
"""
from testing.metrics.context_recall import compute_context_recall #Evaluate retrieval coverage: Measures how much of the reference (ground-truth) answer is supported by the retrieved context.
"""
question: str,
contexts: List[str],
reference_answer: str,
call_gemini,
max_retries: int = 5
"""
from testing.metrics.coverage import compute_coverage #Measures how completely a model’s response covers the factual content of a reference (ground-truth) answer.
"""
question: str,
reference: str,
response: str,
call_gemini,
max_retries: int = 5
"""
from testing.metrics.rouge import compute_rouge
#Calculate F-1 of lexical overlap by LCS: longest common subsequence (in terms of word order, adjacency not required)
#Precision = len(LCS) / len(Answer)
#Recall = len(LCS) / len(Ref)
"""
answer: str,
ground_truth: str,
rouge_type: str = "rougeL",
mode: str = "fmeasure"
"""
from testing.metrics.accuracy import compute_answer_accuracy
"""
question: str,
answer: str,
ground_truth: str,
call_gemini,
create_embedding,
weights: List[float] = [0.75, 0.25],
beta: float = 1.0,
max_retries: int = 5
"""
print("Import evaluation functions")

Import evaluation functions

In [5]:
import pandas as pd
medical_questions_answered_loaded = pd.read_parquet("data/medical_questions_answered.parquet")
relevant_questions = medical_questions_answered_loaded[medical_questions_answered_loaded["question_type"] == "Fact Retrieval"]
question_ids = relevant_questions['id'].to_list()
relevant_questions

,id,source,question,answer,question_type,evidence,evidence_relations,LLM_answer,LLM_context,LLM_tokens
0,Medical-73586ddc,Medical,What is the most common type of skin cancer?,Basal cell carcinoma (BCC) is the most common ...,Fact Retrieval,Basal cell carcinoma (BCC) is the most common ...,Basal cell carcinoma (BCC) is the most common ...,"Basal cell skin cancer, also known as basal ce...",Squamous cell skin cancer (CSCC) is the second...,24381.0
1,Medical-a8bad1cf,Medical,From which cell type does basal cell carcinoma...,Basal cell carcinoma arises from basal cells i...,Fact Retrieval,Basal cell carcinoma arises from basal cells.;...,BCC arises from basal cells in the lower part ...,Basal cell carcinoma arises when basal cells i...,"Basal cell skin cancer, also known as basal ce...",4113.0
2,Medical-422500d5,Medical,Which anatomical locations are most commonly a...,BCC most commonly develops in sun-exposed area...,Fact Retrieval,BCC most commonly develops in sun-exposed area...,BCC most commonly develops in sun-exposed area...,Basal cell carcinoma most commonly affects sun...,Basal cell skin cancer can affect anyone but i...,3514.0
3,Medical-6d2a190d,Medical,What is the primary risk factor for basal cell...,UV radiation exposure is a primary risk factor...,Fact Retrieval,UV radiation exposure is a primary risk factor...,UV radiation exposure is a primary risk factor...,The primary risk factor for basal cell carcino...,Basal cell skin cancer can affect anyone but i...,6428.0
4,Medical-5ad931db,Medical,How does fair skin affect the risk of developi...,Fair skin increases the risk of BCC.,Fact Retrieval,Fair skin increases the risk of BCC.,"Fair skin, light hair, and light eye color inc...",Fair skin increases the risk of developing Bas...,Basal cell skin cancer can affect anyone but i...,8562.0
...,...,...,...,...,...,...,...,...,...,...
1093,Medical-329de573,Medical,What should be discussed before starting breas...,Fertility preservation should be discussed bef...,Fact Retrieval,Fertility preservation should be discussed bef...,Fertility preservation should be discussed bef...,"Before starting breast cancer treatment, indiv...",Patients who wish to have children after cance...,27329.0
1094,Medical-e79a7e61,Medical,What patient factor is considered in treatment...,Performance status is considered in treatment ...,Fact Retrieval,Performance status is considered in treatment ...,Performance status is considered in treatment ...,Patient factors considered in treatment planni...,Treatment planning for patients starts with te...,28422.0
1095,Medical-883feb97,Medical,What does follow-up for breast cancer include?,"Follow-up includes imaging, physical exams, an...",Fact Retrieval,Follow-up for breast cancer includes imaging.;...,"Follow-up includes imaging, physical exams, an...","For breast cancer, follow-up and surveillance ...","""FOLLOW-UP AND SURVEILLANCE"" stands as the vig...",28392.0
1096,Medical-53f6f364,Medical,Which breast cancer subtype commonly presents ...,Inflammatory breast cancer (IBC) commonly pres...,Fact Retrieval,Inflammatory breast cancer (IBC) commonly pres...,Inflammatory breast cancer (IBC): Symptom: Red...,Inflammatory breast cancer (IBC) commonly pres...,Inflammatory breast cancer (IBC) is challengin...,6546.0
1097,Medical-6598f21c,Medical,What is the main symptom of metastatic breast ...,Bone pain is a main symptom of metastatic brea...,Fact Retrieval,Bone pain is a main symptom of metastatic brea...,Metastatic breast cancer (MBC): Symptom: Bone ...,Bone pain can be a symptom indicating the prog...,Breast cancer originates from epithelial cells...,11523.0

In [6]:
try:
    medical_questions_evaluated = pd.read_parquet("data/evaluations/fact_retrieval_evaluated.parquet")
    medical_questions_evaluated = (
        medical_questions_evaluated
        .set_index("qid")
        .to_dict(orient="index")
    )
except:
    medical_questions_evaluated = {}


medical_questions_evaluated

{}

In [7]:
def both_valid(a, b):
    return (
        a is not None and b is not None
        and not np.isnan(a)
        and not np.isnan(b)
    )

In [8]:
#accuracy
#rouge-L

from tqdm import tqdm
import time
sep = "\n\n" + "-"*100 + "\n\n"
MAX_RETRIES = 10
SLEEP_SEC = 30

def get_answers():
    for qid in tqdm(question_ids):
        if qid in medical_questions_evaluated:
            continue

        row = relevant_questions.loc[relevant_questions["id"] == qid].iloc[0]
        row_eval = {}

        question = row["question"]
        reference = row["answer"]
        answer = row["LLM_answer"]
        
        rouge_score = compute_rouge(answer, reference)
        accuracy, tokens = None, None
        for attempt in range(1, MAX_RETRIES + 1):
            try:
                accuracy, tokens = compute_answer_accuracy(question, answer, reference, call_gemini, create_embedding)
                break
            except Exception as e:
                code = e.error.code if hasattr(e, "error") else e
                print(f"[ERROR] qid={qid} failed after {attempt} retries: {code}")
                if attempt == MAX_RETRIES:
                    return
                time.sleep(SLEEP_SEC * attempt)  #backoff
        if both_valid(accuracy, tokens):
            row_eval["accuracy"] = accuracy
            row_eval["rouge"] = rouge_score
            row_eval["tokens"] = tokens
            medical_questions_evaluated[qid] = row_eval
get_answers()

100%|██████████| 1098/1098 [5:47:22<00:00, 18.98s/it]

In [9]:
medical_questions_evaluated

{'Medical-73586ddc': {'accuracy': 0.9964528679097717,
  'rouge': 0.7741935483870968,
  'tokens': 1799},
 'Medical-a8bad1cf': {'accuracy': 0.7241071759987783,
  'rouge': 0.6206896551724138,
  'tokens': 6419},
 'Medical-422500d5': {'accuracy': 0.7276801466441833,
  'rouge': 0.48000000000000004,
  'tokens': 7103},
 'Medical-6d2a190d': {'accuracy': 0.6030602305658799,
  'rouge': 0.19047619047619047,
  'tokens': 2423},
 'Medical-5ad931db': {'accuracy': 0.44477821671216744,
  'rouge': 0.2641509433962264,
  'tokens': 2763},
 'Medical-6b0f8bc4': {'accuracy': 0.725485593013854,
  'rouge': 0.2857142857142857,
  'tokens': 1526},
 'Medical-75c9949b': {'accuracy': 0.9880138634510376,
  'rouge': 0.56,
  'tokens': 1177},
 'Medical-ec091b24': {'accuracy': 0.5310109585163605,
  'rouge': 0.34782608695652173,
  'tokens': 2964},
 'Medical-8d39da2e': {'accuracy': 0.8448711335190278,
  'rouge': 0.41304347826086957,
  'tokens': 5387},
 'Medical-88c0b2ba': {'accuracy': 0.22807148098945618,
  'rouge': 0.15384615384615385,
  'tokens': 3874},
 'Medical-a8ee8ba1': {'accuracy': 0.9908454417057373,
  'rouge': 0.631578947368421,
  'tokens': 1093},
 'Medical-ec7d8801': {'accuracy': 0.43036949419229287,
  'rouge': 0.17910447761194026,
  'tokens': 3467},
 'Medical-9797af69': {'accuracy': 0.9859103857845917,
  'rouge': 0.48000000000000004,
  'tokens': 3187},
 'Medical-6884d3fa': {'accuracy': 0.5913442968947205,
  'rouge': 0.2608695652173913,
  'tokens': 6025},
 'Medical-fc6d1c33': {'accuracy': 0.9692876934255188,
  'rouge': 0.35000000000000003,
  'tokens': 4444},
 'Medical-97abee55': {'accuracy': 0.659509132972503,
  'rouge': 0.4782608695652174,
  'tokens': 2436},
 'Medical-28d1e2d7': {'accuracy': 0.6040059625633698,
  'rouge': 0.3720930232558139,
  'tokens': 1902},
 'Medical-4cf524cb': {'accuracy': 0.5214685231087219,
  'rouge': 0.17391304347826086,
  'tokens': 2688},
 'Medical-df1408f4': {'accuracy': 0.9870614259310104,
  'rouge': 0.6285714285714286,
  'tokens': 2324},
 'Medical-17ae12cd': {'accuracy': 0.5985812842377167,
  'rouge': 0.3636363636363636,
  'tokens': 2129},
 'Medical-965ad8a8': {'accuracy': 0.5386537064775283,
  'rouge': 0.10958904109589043,
  'tokens': 5870},
 'Medical-5175a85e': {'accuracy': 0.46666584906045583,
  'rouge': 0.20338983050847456,
  'tokens': 4549},
 'Medical-5f2cb8a5': {'accuracy': 0.5152099012848552,
  'rouge': 0.2631578947368421,
  'tokens': 3764},
 'Medical-0429f83c': {'accuracy': 0.40037980672416074,
  'rouge': 0.2903225806451613,
  'tokens': 2833},
 'Medical-152bec6a': {'accuracy': 0.9701187609876221,
  'rouge': 0.5714285714285714,
  'tokens': 2947},
 'Medical-e3923e5f': {'accuracy': 0.7352147697902405,
  'rouge': 0.358974358974359,
  'tokens': 2891},
 'Medical-0c2f999d': {'accuracy': 0.9884761868782379,
  'rouge': 0.6842105263157894,
  'tokens': 5204},
 'Medical-b6dc1118': {'accuracy': 0.21636568009853363,
  'rouge': 0.35,
  'tokens': 5287},
 'Medical-ba2c8007': {'accuracy': 0.2315109670162201,
  'rouge': 0.5714285714285715,
  'tokens': 6128},
 'Medical-5c30dd24': {'accuracy': 0.21969975531101227,
  'rouge': 0.09302325581395347,
  'tokens': 3897},
 'Medical-8622e4cc': {'accuracy': 0.8263856976624351,
  'rouge': 0.2857142857142857,
  'tokens': 3216},
 'Medical-b0b58bf2': {'accuracy': 0.605268418742035,
  'rouge': 0.5116279069767442,
  'tokens': 3741},
 'Medical-90704d0a': {'accuracy': 0.8218496500845771,
  'rouge': 0.6285714285714286,
  'tokens': 3748},
 'Medical-941c0004': {'accuracy': 0.7299658953643524,
  'rouge': 0.42307692307692313,
  'tokens': 3806},
 'Medical-4bb300c3': {'accuracy': 0.7290622442294072,
  'rouge': 0.21052631578947364,
  'tokens': 1496},
 'Medical-acec9fa2': {'accuracy': 0.4754215180582204,
  'rouge': 0.21428571428571427,
  'tokens': 2446},
 'Medical-7c81f966': {'accuracy': 0.7303612827588033,
  'rouge': 0.2702702702702703,
  'tokens': 3059},
 'Medical-f6b5155a': {'accuracy': 0.9879262148208954,
  'rouge': 0.6428571428571429,
  'tokens': 1200},
 'Medical-4061f8c4': {'accuracy': 0.7277423738933289,
  'rouge': 0.3684210526315789,
  'tokens': 3059},
 'Medical-89de49a4': {'accuracy': 0.6888065784788743,
  'rouge': 0.4,
  'tokens': 5593},
 'Medical-624c452d': {'accuracy': 0.6516103850507478,
  'rouge': 0.15151515151515152,
  'tokens': 5119},
 'Medical-4aab8ef7': {'accuracy': 0.9945920555658676,
  'rouge': 0.7777777777777777,
  'tokens': 1067},
 'Medical-bc412bb6': {'accuracy': 0.8599660928209235,
  'rouge': 0.23188405797101452,
  'tokens': 2863},
 'Medical-cb249d9b': {'accuracy': 0.9860697388023987,
  'rouge': 0.5531914893617021,
  'tokens': 3664},
 'Medical-e506aa4e': {'accuracy': 0.7237050532628011,
  'rouge': 0.5,
  'tokens': 3116},
 'Medical-14cee623': {'accuracy': 0.512337851488353,
  'rouge': 0.26666666666666666,
  'tokens': 3775},
 'Medical-ae28e711': {'accuracy': 0.47738420960370687,
  'rouge': 0.3137254901960785,
  'tokens': 3626},
 'Medical-2bef6940': {'accuracy': 0.6005047708281022,
  'rouge': 0.38095238095238093,
  'tokens': 1846},
 'Medical-0047c320': {'accuracy': 0.6093120872505646,
  'rouge': 0.2857142857142857,
  'tokens': 2562},
 'Medical-ca377f8d': {'accuracy': 0.4007344643089758,
  'rouge': 0.23333333333333334,
  'tokens': 4084},
 'Medical-0b2a33fc': {'accuracy': 0.6040609478481751,
  'rouge': 0.6399999999999999,
  'tokens': 4295},
 'Medical-de0b30b1': {'accuracy': 0.47184434530202535,
  'rouge': 0.2790697674418604,
  'tokens': 2744},
 'Medical-4f1779a5': {'accuracy': 0.6082801520355683,
  'rouge': 0.32,
  'tokens': 1970},
 'Medical-d675eecd': {'accuracy': 0.9732561557360031,
  'rouge': 0.5294117647058824,
  'tokens': 2306},
 'Medical-7e4192af': {'accuracy': 0.4715477227873006,
  'rouge': 0.34285714285714286,
  'tokens': 4913},
 'Medical-f8b6c41e': {'accuracy': 0.6000895201691132,
  'rouge': 0.4444444444444444,
  'tokens': 2292},
 'Medical-cef34fff': {'accuracy': 0.38661904133376856,
  'rouge': 0.08955223880597013,
  'tokens': 4296},
 'Medical-27280ca7': {'accuracy': 0.8167084961529594,
  'rouge': 0.24390243902439024,
  'tokens': 2945},
 'Medical-04249246': {'accuracy': 0.8344473599787574,
  'rouge': 0.3111111111111111,
  'tokens': 2128},
 'Medical-3e18a314': {'accuracy': 0.3962637732130029,
  'rouge': 0.2142857142857143,
  'tokens': 3443},
 'Medical-34ad11ec': {'accuracy': 0.20227333903312683,
  'rouge': 0.14285714285714285,
  'tokens': 5349},
 'Medical-74440a6a': {'accuracy': 0.8167082726355415,
  'rouge': 0.25000000000000006,
  'tokens': 1999},
 'Medical-a296a86b': {'accuracy': 0.18769347667694092,
  'rouge': 0.2105263157894737,
  'tokens': 3002},
 'Medical-f907720b': {'accuracy': 0.6029828190334778,
  'rouge': 0.41379310344827586,
  'tokens': 5345},
 'Medical-f80cbf85': {'accuracy': 0.4140103161124054,
  'rouge': 0.13636363636363635,
  'tokens': 5273},
 'Medical-b3c430ef': {'accuracy': 0.993096649571759,
  'rouge': 0.8181818181818181,
  'tokens': 2705},
 'Medical-304b0354': {'accuracy': 0.9989702998966827,
  'rouge': 0.9600000000000001,
  'tokens': 1571},
 'Medical-bc34a6a1': {'accuracy': 0.7702227085336594,
  'rouge': 0.21052631578947367,
  'tokens': 3735},
 'Medical-b1a95144': {'accuracy': 0.22152790427207947,
  'rouge': 0.2857142857142857,
  'tokens': 5560},
 'Medical-473eae59': {'accuracy': 0.1967105269432068,
  'rouge': 0.1568627450980392,
  'tokens': 3257},
 'Medical-1b824083': {'accuracy': 0.721626698904128,
  'rouge': 0.48275862068965514,
  'tokens': 1730},
 'Medical-ba9d39eb': {'accuracy': 0.4632101058668294,
  'rouge': 0.12244897959183672,
  'tokens': 2700},
 'Medical-e306413c': {'accuracy': 0.17707403004169464,
  'rouge': 0.08333333333333334,
  'tokens': 5725},
 'Medical-64ef6350': {'accuracy': 0.21264106035232544,
  'rouge': 0.15384615384615385,
  'tokens': 6674},
 'Medical-e05d0922': {'accuracy': 0.724061340026946,
  'rouge': 0.3018867924528302,
  'tokens': 3059},
 'Medical-1c1492e7': {'accuracy': 0.8220932542797741,
  'rouge': 0.1875,
  'tokens': 5041},
 'Medical-dba48e64': {'accuracy': 0.7200188934136342,
  'rouge': 0.5217391304347827,
  'tokens': 2759},
 'Medical-f5fc9016': {'accuracy': 0.23175570368766785,
  'rouge': 0.6666666666666666,
  'tokens': 3272},
 'Medical-b80bf4c5': {'accuracy': 0.9824578462906219,
  'rouge': 0.3703703703703703,
  'tokens': 1329},
 'Medical-3978515f': {'accuracy': 0.5074953615185436,
  'rouge': 0.20833333333333334,
  'tokens': 3119},
 'Medical-afabde7f': {'accuracy': 0.7013188600092244,
  'rouge': 0.22222222222222224,
  'tokens': 4737},
 'Medical-a4081e18': {'accuracy': 0.5873040705356766,
  'rouge': 0.4210526315789474,
  'tokens': 2505},
 'Medical-79a788b8': {'accuracy': 0.9616177527971603,
  'rouge': 0.23076923076923078,
  'tokens': 1567},
 'Medical-c99256ce': {'accuracy': 0.4792503483923682,
  'rouge': 0.19047619047619047,
  'tokens': 3890},
 'Medical-7b5a8ac6': {'accuracy': 0.388150364139444,
  'rouge': 0.27999999999999997,
  'tokens': 2724},
 'Medical-26033837': {'accuracy': 0.19797642529010773,
  'rouge': 0.2962962962962963,
  'tokens': 1262},
 'Medical-9f3a0a90': {'accuracy': 0.5810867249496918,
  'rouge': 0.375,
  'tokens': 1551},
 'Medical-f619b6ea': {'accuracy': 0.41242426631725465,
  'rouge': 0.21875,
  'tokens': 3176},
 'Medical-9474c5bb': {'accuracy': 0.6297993758892924,
  'rouge': 0.22222222222222224,
  'tokens': 8451},
 'Medical-5825991f': {'accuracy': 0.17884697020053864,
  'rouge': 0.1311475409836066,
  'tokens': 2841},
 'Medical-a4dcffa3': {'accuracy': 0.9972749649853363,
  'rouge': 0.888888888888889,
  'tokens': 1931},
 'Medical-3919018c': {'accuracy': 0.9949341117210724,
  'rouge': 0.8695652173913044,
  'tokens': 1598},
 'Medical-d7180179': {'accuracy': 0.976324736996991,
  'rouge': 0.4166666666666667,
  'tokens': 2393},
 'Medical-f05a2e9b': {'accuracy': 0.783819830376133,
  'rouge': 0.05333333333333334,
  'tokens': 6006},
 'Medical-5b1265c0': {'accuracy': 0.9999999998875,
  'rouge': 1.0,
  'tokens': 1191},
 'Medical-d1e50927': {'accuracy': 0.7150449156261169,
  'rouge': 0.3225806451612903,
  'tokens': 3461},
 'Medical-9536f8e7': {'accuracy': 0.6257183876458293,
  'rouge': 0.3870967741935483,
  'tokens': 8269},
 'Medical-1f290988': {'accuracy': 0.7315765022731506,
  'rouge': 0.42105263157894735,
  'tokens': 2303},
 'Medical-3d21bfb3': {'accuracy': 0.8315270602249761,
  'rouge': 0.53125,
  'tokens': 4899},
 'Medical-a2555661': {'accuracy': 0.8207862287159782,
  'rouge': 0.39999999999999997,
  'tokens': 5462},
 'Medical-8866282b': {'accuracy': 0.8167935072775703,
  'rouge': 0.24390243902439024,
  'tokens': 2278},
 'Medical-77287c53': {'accuracy': 0.7907186448081879,
  'rouge': 0.26086956521739124,
  'tokens': 7109},
 'Medical-d9522675': {'accuracy': 0.20180797576904297,
  'rouge': 0.2222222222222222,
  'tokens': 2822},
 'Medical-8fe8663f': {'accuracy': 0.8578077256210785,
  'rouge': 0.375,
  'tokens': 6121},
 'Medical-c421a232': {'accuracy': 0.2387484312057495,
  'rouge': 0.4102564102564102,
  'tokens': 4015},
 'Medical-203a2d6b': {'accuracy': 0.6413913991896752,
  'rouge': 0.38202247191011235,
  'tokens': 4048},
 'Medical-dc52ffce': {'accuracy': 0.5624387909524249,
  'rouge': 0.28571428571428575,
  'tokens': 4223},
 'Medical-0d21d2d6': {'accuracy': 0.6857149004508484,
  'rouge': 0.18390804597701152,
  'tokens': 6938},
 'Medical-bfa9a27b': {'accuracy': 0.6654696421616888,
  'rouge': 0.25,
  'tokens': 12842},
 'Medical-8d545fa4': {'accuracy': 0.8839872578330781,
  'rouge': 0.17857142857142855,
  'tokens': 6121},
 'Medical-6a38af6d': {'accuracy': 0.5776844322118927,
  'rouge': 0.3414634146341463,
  'tokens': 1973},
 'Medical-eac1c791': {'accuracy': 0.5956441461612865,
  'rouge': 0.3414634146341463,
  'tokens': 7214},
 'Medical-8bf3a99b': {'accuracy': 0.5748559744514203,
  'rouge': 0.22500000000000003,
  'tokens': 3929},
 'Medical-c8c9c0ee': {'accuracy': 0.8138032465719839,
  'rouge': 0.1842105263157895,
  'tokens': 6823},
 'Medical-b1ab4938': {'accuracy': 0.17533400654792786,
  'rouge': 0.059701492537313446,
  'tokens': 6152},
 'Medical-1edadd2a': {'accuracy': 0.6290756122977975,
  'rouge': 0.25396825396825395,
  'tokens': 4331},
 'Medical-59292b3b': {'accuracy': 0.42265231904086453,
  'rouge': 0.38596491228070173,
  'tokens': 4997},
 'Medical-909f9360': {'accuracy': 0.7281299828983032,
  'rouge': 0.3142857142857142,
  'tokens': 5556},
 'Medical-9a719269': {'accuracy': 0.19878245890140533,
  'rouge': 0.08,
  'tokens': 6249},
 'Medical-f10f3bc4': {'accuracy': 0.7060416638403249,
  'rouge': 0.2368421052631579,
  'tokens': 5056},
 'Medical-d8a3772b': {'accuracy': 0.7311521768088465,
  'rouge': 0.37499999999999994,
  'tokens': 6425},
 'Medical-2a0d5063': {'accuracy': 0.4710958301562693,
  'rouge': 0.22988505747126434,
  'tokens': 3994},
 'Medical-ff41533a': {'accuracy': 0.730284467272849,
  'rouge': 0.18749999999999997,
  'tokens': 3576},
 'Medical-c87c6baf': {'accuracy': 0.5585264173465028,
  'rouge': 0.23728813559322035,
  'tokens': 3422},
 'Medical-3e2b82f5': {'accuracy': 0.20575150847434998,
  'rouge': 0.14285714285714285,
  'tokens': 8021},
 'Medical-0c8340a1': {'accuracy': 0.9929611085720398,
  'rouge': 0.8235294117647058,
  'tokens': 1096},
 'Medical-9b293f2c': {'accuracy': 0.5225774824259293,
  'rouge': 0.2641509433962264,
  'tokens': 3662},
 'Medical-e49be454': {'accuracy': 0.9899014978850906,
  'rouge': 0.4375,
  'tokens': 4363},
 'Medical-c97b2e2b': {'accuracy': 0.7123379706836426,
  'rouge': 0.2456140350877193,
  'tokens': 4982},
 'Medical-e5676a79': {'accuracy': 0.9890832601852753,
  'rouge': 0.5000000000000001,
  'tokens': 4364},
 'Medical-fad73295': {'accuracy': 0.9843099861587112,
  'rouge': 0.6249999999999999,
  'tokens': 7435},
 'Medical-77457615': {'accuracy': 0.22837236523628235,
  'rouge': 0.15384615384615385,
  'tokens': 7126},
 'Medical-9fb94929': {'accuracy': 0.47596369679575856,
  'rouge': 0.2181818181818182,
  'tokens': 5489},
 'Medical-b3eac8b2': {'accuracy': 0.7308644353676748,
  'rouge': 0.3636363636363636,
  'tokens': 4942},
 'Medical-72a77731': {'accuracy': 0.9849599449701645,
  'rouge': 0.5000000000000001,
  'tokens': 1368},
 'Medical-5fe38d4e': {'accuracy': 0.6612964229495767,
  'rouge': 0.26666666666666666,
  'tokens': 3976},
 'Medical-69537d43': {'accuracy': 0.8747693682868888,
  'rouge': 0.36065573770491804,
  'tokens': 4366},
 'Medical-6d738949': {'accuracy': 0.9727315603561737,
  'rouge': 0.38461538461538464,
  'tokens': 2164},
 'Medical-7da67d67': {'accuracy': 0.515551346504451,
  'rouge': 0.21739130434782608,
  'tokens': 5927},
 'Medical-3170a5f2': {'accuracy': 0.8378167509432655,
  'rouge': 0.46153846153846156,
  'tokens': 2564},
 'Medical-dc60c354': {'accuracy': 0.828279396831594,
  'rouge': 0.4166666666666667,
  'tokens': 5907},
 'Medical-62a9b979': {'accuracy': 0.5109517156717789,
  'rouge': 0.1702127659574468,
  'tokens': 3663},
 'Medical-57375967': {'accuracy': 0.606045529203622,
  'rouge': 0.35294117647058826,
  'tokens': 6405},
 'Medical-7044a5ef': {'accuracy': 0.2233904004096985,
  'rouge': 0.3125,
  'tokens': 5052},
 'Medical-c2ab6e9a': {'accuracy': 0.5548620422347839,
  'rouge': 0.1714285714285714,
  'tokens': 3366},
 'Medical-61ec9250': {'accuracy': 0.9666327236957886,
  'rouge': 0.23076923076923078,
  'tokens': 1655},
 'Medical-cbbc0e25': {'accuracy': 0.9621938913498093,
  'rouge': 0.26666666666666666,
  'tokens': 4159},
 'Medical-5c8f25b0': {'accuracy': 0.5206327318785202,
  'rouge': 0.4651162790697675,
  'tokens': 4753},
 'Medical-9b7aadb2': {'accuracy': 0.18474355340003967,
  'rouge': 0.07843137254901962,
  'tokens': 1663},
 'Medical-f18cea43': {'accuracy': 0.21180543303489685,
  'rouge': 0.19753086419753085,
  'tokens': 6570},
 'Medical-e2848d7f': {'accuracy': 0.9685285984719818,
  'rouge': 0.4,
  'tokens': 2089},
 'Medical-e1b6447e': {'accuracy': 0.5871329158075791,
  'rouge': 0.31372549019607837,
  'tokens': 5464},
 'Medical-7db5b20d': {'accuracy': 0.8350437938567024,
  'rouge': 0.24242424242424243,
  'tokens': 1514},
 'Medical-ea3d4859': {'accuracy': 0.5145280539629471,
  'rouge': 0.3157894736842105,
  'tokens': 2470},
 'Medical-8109c3aa': {'accuracy': 0.19760185480117798,
  'rouge': 0.15,
  'tokens': 3213},
 'Medical-ba894e2c': {'accuracy': 0.9646546541894501,
  'rouge': 0.21621621621621623,
  'tokens': 4962},
 'Medical-622cb4e3': {'accuracy': 0.9960356055565216,
  'rouge': 0.782608695652174,
  'tokens': 1254},
 'Medical-42f1975a': {'accuracy': 0.23700174689292908,
  'rouge': 0.4117647058823529,
  'tokens': 3039},
 'Medical-419cadfe': {'accuracy': 0.6578425274938158,
  'rouge': 0.4117647058823529,
  'tokens': 5473},
 'Medical-8be16d47': {'accuracy': 0.5538012889342561,
  'rouge': 0.3255813953488372,
  'tokens': 3905},
 'Medical-9e7500a0': {'accuracy': 0.7261840998626434,
  'rouge': 0.5555555555555556,
  'tokens': 3543},
 'Medical-a61abd42': {'accuracy': 0.9868476985760071,
  'rouge': 0.5,
  'tokens': 1154},
 'Medical-74016ca7': {'accuracy': 0.7255678921271276,
  'rouge': 0.5454545454545454,
  'tokens': 2537},
 'Medical-bffd01c2': {'accuracy': 0.9791569112981384,
  'rouge': 0.4,
  'tokens': 2732},
 'Medical-ef451592': {'accuracy': 0.7329919337559652,
  'rouge': 0.5714285714285714,
  'tokens': 2682},
 'Medical-e1aa3f36': {'accuracy': 0.5375704049704086,
  'rouge': 0.41666666666666663,
  'tokens': 3711},
 'Medical-83b8a631': {'accuracy': 0.6027845441826325,
  'rouge': 0.2564102564102564,
  'tokens': 2152},
 'Medical-2c702150': {'accuracy': 0.5108097970125687,
  'rouge': 0.26086956521739135,
  'tokens': 2552},
 'Medical-5bae1c96': {'accuracy': 0.4943422593506583,
  'rouge': 0.22222222222222224,
  'tokens': 6271},
 'Medical-a5c06d63': {'accuracy': 0.6035053282507401,
  'rouge': 0.3333333333333333,
  'tokens': 3421},
 'Medical-4de99f79': {'accuracy': 0.5210540323969539,
  'rouge': 0.19672131147540986,
  'tokens': 2322},
 'Medical-ebb0af4d': {'accuracy': 0.7884718477210358,
  'rouge': 0.372093023255814,
  'tokens': 5535},
 'Medical-8217a825': {'accuracy': 0.9975506364174225,
  'rouge': 0.7,
  'tokens': 1023},
 'Medical-0cb322e0': {'accuracy': 0.6116307675369721,
  'rouge': 0.41025641025641024,
  'tokens': 1617},
 'Medical-64042235': {'accuracy': 0.9095876464821361,
  'rouge': 0.5245901639344263,
  'tokens': 6622},
 'Medical-b4100b78': {'accuracy': 0.8288144230242591,
  'rouge': 0.3783783783783784,
  'tokens': 4101},
 'Medical-d2bac092': {'accuracy': 0.4030775725443085,
  'rouge': 0.18181818181818182,
  'tokens': 5508},
 'Medical-eab59fae': {'accuracy': 0.48160123820906575,
  'rouge': 0.29166666666666663,
  'tokens': 4472},
 'Medical-61cf41ee': {'accuracy': 0.5117823659998688,
  'rouge': 0.2692307692307692,
  'tokens': 3162},
 'Medical-09d21113': {'accuracy': 0.9813328384728088,
  'rouge': 0.6,
  'tokens': 3272},
 'Medical-1b7a0e02': {'accuracy': 0.7817017435511903,
  'rouge': 0.16000000000000003,
  'tokens': 3601},
 'Medical-b77be62e': {'accuracy': 0.7837267219528107,
  'rouge': 0.27999999999999997,
  'tokens': 2374},
 'Medical-752ca0c2': {'accuracy': 0.6619192467839959,
  'rouge': 0.38095238095238093,
  'tokens': 3834},
 'Medical-4ae5ec38': {'accuracy': 0.41763073202666623,
  'rouge': 0.2769230769230769,
  'tokens': 4867},
 'Medical-2f2b791e': {'accuracy': 0.20372778177261353,
  'rouge': 0.16666666666666669,
  'tokens': 4771},
 'Medical-563587c2': {'accuracy': 0.7162642776424428,
  'rouge': 0.30508474576271183,
  'tokens': 3560},
 'Medical-6aaabde4': {'accuracy': 0.5983159988649827,
  'rouge': 0.3684210526315789,
  'tokens': 1820},
 'Medical-2e9466a9': {'accuracy': 0.6021186261973324,
  'rouge': 0.33766233766233766,
  'tokens': 6072},
 'Medical-d2746bf8': {'accuracy': 0.9961094706125595,
  'rouge': 0.5833333333333334,
  'tokens': 1295},
 'Medical-75f181e8': {'accuracy': 0.5187952398893845,
  'rouge': 0.32258064516129037,
  'tokens': 1971},
 'Medical-de0767ce': {'accuracy': 0.6371219711215738,
  'rouge': 0.2424242424242424,
  'tokens': 4798},
 'Medical-d5c10dcf': {'accuracy': 0.8131030558939796,
  'rouge': 0.7272727272727273,
  'tokens': 3526},
 'Medical-bb9550cb': {'accuracy': 0.722494870357604,
  'rouge': 0.5806451612903225,
  'tokens': 2935},
 'Medical-85c57bc9': {'accuracy': 0.18158677220344543,
  'rouge': 0.18749999999999997,
  'tokens': 2206},

In [10]:
df_eval = (
    pd.DataFrame.from_dict(medical_questions_evaluated, orient="index")
      .reset_index()
      .rename(columns={"index": "qid"})
)

In [11]:
df_eval.to_parquet("data/evaluations/fact_retrieval_evaluated.parquet")
df_eval_loaded = pd.read_parquet("data/evaluations/fact_retrieval_evaluated.parquet")
df_eval_loaded

                   qid  accuracy     rouge  tokens
0     Medical-73586ddc  0.996453  0.774194    1799
1     Medical-a8bad1cf  0.724107  0.620690    6419
2     Medical-422500d5  0.727680  0.480000    7103
3     Medical-6d2a190d  0.603060  0.190476    2423
4     Medical-5ad931db  0.444778  0.264151    2763
...                ...       ...       ...     ...
1093  Medical-329de573  0.468845  0.100000    4088
1094  Medical-e79a7e61  0.427511  0.200000    5180
1095  Medical-883feb97  0.929114  0.131579    7368
1096  Medical-53f6f364  0.668135  0.684211    5972
1097  Medical-6598f21c  0.825405  0.500000    4585

[1098 rows x 4 columns]

In [12]:
print("min:", df_eval_loaded["tokens"].min())
print("max:", df_eval_loaded["tokens"].max())
print("avg:", df_eval_loaded["tokens"].mean())
print("sum:", df_eval_loaded["tokens"].sum())

min: 997
max: 12842
avg: 3850.6593806921674
sum: 4228024

In [13]:
print("min:", df_eval_loaded["accuracy"].min())
print("max:", df_eval_loaded["accuracy"].max())
print("avg:", df_eval_loaded["accuracy"].mean())
print("sum:", df_eval_loaded["accuracy"].sum())

min: 0.16753409802913666
max: 0.999999999925
avg: 0.6438947848796382
sum: 706.9964737978428

In [14]:
print("min:", df_eval_loaded["rouge"].min())
print("max:", df_eval_loaded["rouge"].max())
print("avg:", df_eval_loaded["rouge"].mean())
print("sum:", df_eval_loaded["rouge"].sum())

min: 0.044444444444444446
max: 1.0
avg: 0.35954513686712053
sum: 394.78056028009837