In [1]:
from sentence_transformers import SentenceTransformer
import torch
# Load embedding model
device = "cuda" if torch.cuda.is_available() else "cpu"
model = SentenceTransformer("google/embeddinggemma-300m", device=device)

def create_embedding(texts):
    if type(texts) == list: # the input param is a list contains text chunks
        embeddings = model.encode(texts)
        return embeddings
    elif type(texts) == str: # just one text chunk
        embedding = model.encode([texts])
        return embedding
    else:
        raise ValueError("The texts paramters should be str or list[str]")

print(device)

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

cuda

In [2]:
import os
dir_path = os.getcwd()
print("The directory of this script is:", dir_path)
root_path = os.path.dirname(dir_path)
print("The root directory is:", root_path)

The directory of this script is: d:\Documents\GitHub\NodeRAG\testing
The root directory is: d:\Documents\GitHub\NodeRAG

In [3]:
#LLM api call
from google import genai
with open(f"{root_path}/API_KEY.txt", "r", encoding="utf-8") as f:
    API_KEY = f.read()

def call_gemini(text):
    client = genai.Client(api_key = API_KEY)
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=text
    )
    return response.text, response.usage_metadata.total_token_count

In [4]:
import sys
import numpy as np
sys.path.append(root_path)
from testing.metrics.faithfulness import compute_faithfulness #Detect hallucinations: Measures how much the LLM answer is based on the retrieved context
"""
question: str,
answer: str,
contexts: List[str],
call_gemini,
max_retries: int = 5
"""
from testing.metrics.context_recall import compute_context_recall #Evaluate retrieval coverage: Measures how much of the reference (ground-truth) answer is supported by the retrieved context.
"""
question: str,
contexts: List[str],
reference_answer: str,
call_gemini,
max_retries: int = 5
"""
from testing.metrics.coverage import compute_coverage #Measures how completely a model’s response covers the factual content of a reference (ground-truth) answer.
"""
question: str,
reference: str,
response: str,
call_gemini,
max_retries: int = 5
"""
from testing.metrics.rouge import compute_rouge
#Calculate F-1 of lexical overlap by LCS: longest common subsequence (in terms of word order, adjacency not required)
#Precision = len(LCS) / len(Answer)
#Recall = len(LCS) / len(Ref)
"""
answer: str,
ground_truth: str,
rouge_type: str = "rougeL",
mode: str = "fmeasure"
"""
from testing.metrics.accuracy import compute_answer_accuracy
"""
question: str,
answer: str,
ground_truth: str,
call_gemini,
create_embedding,
weights: List[float] = [0.75, 0.25],
beta: float = 1.0,
max_retries: int = 5
"""
print("Import evaluation functions")

Import evaluation functions

In [5]:
import pandas as pd
medical_questions_answered_loaded = pd.read_parquet("data/medical_questions_answered.parquet")
relevant_questions = medical_questions_answered_loaded[medical_questions_answered_loaded["question_type"] == "Contextual Summarize"]
question_ids = relevant_questions['id'].to_list()
relevant_questions

,id,source,question,answer,question_type,evidence,evidence_relations,LLM_answer,LLM_context,LLM_tokens
1607,Medical-5fd3c02d,Medical,What are the main risk factors associated with...,The main risk factors associated with the deve...,Contextual Summarize,Basal cell carcinoma risk is increased by UV r...,UV radiation exposure is a primary risk factor...,The main risk factors for developing basal cel...,Basal cell skin cancer is caused by exposure t...,8096.0
1608,Medical-b8b22d33,Medical,Which anatomical locations and cell types are ...,Basal cell carcinoma arises from basal cells i...,Contextual Summarize,Basal cell carcinoma arises from basal cells i...,BCC arises from basal cells in the lower part ...,Basal cell carcinoma (BCC) most commonly invol...,Basal cell skin cancer is the most common type...,5781.0
1609,Medical-9c85110b,Medical,What are the typical symptoms and presentation...,Basal cell carcinoma (BCC) typically presents ...,Contextual Summarize,Basal cell carcinoma typically presents as fla...,"BCC presents as flat, pale or yellow areas, re...",Basal cell carcinoma (BCC) typically appears i...,Basal cell skin cancer is the most common type...,6137.0
1610,Medical-fcf87025,Medical,Which diagnostic methods are used to confirm b...,Diagnosis of basal cell carcinoma involves a t...,Contextual Summarize,Diagnosis of basal cell carcinoma involves a c...,Diagnosis of BCC involves medical and family h...,The diagnostic process for basal cell carcinom...,A diagnosis of bone cancer is confirmed using ...,4795.0
1611,Medical-6baf8bff,Medical,What are the standard treatment options for ba...,The standard treatment options for basal cell ...,Contextual Summarize,Surgery is the most common treatment for basal...,Surgery is the most common treatment for BCC; ...,Standard treatment options for basal cell carc...,Standard surgical excision is a recommended tr...,20750.0
...,...,...,...,...,...,...,...,...,...,...
1891,Medical-0cba5d0a,Medical,What are the main risk factors and considerati...,The main risk factors for breast cancer includ...,Contextual Summarize,Major risk factors for breast cancer include f...,"Risk factors include family history, BRCA muta...",Key risk factors for breast cancer include bei...,Questions regarding cancer treatment options c...,10341.0
1892,Medical-d72d7cb9,Medical,How is follow-up and surveillance conducted fo...,Follow-up for breast cancer patients includes ...,Contextual Summarize,Follow-up for breast cancer patients includes ...,"Follow-up includes imaging, physical exams, an...","I am sorry, but the provided context does not ...","After treatment, patients undergo surveillance...",27041.0
1893,Medical-97d64c1f,Medical,What is the clinical significance of tumor gra...,The clinical significance of tumor grade in br...,Contextual Summarize,Tumor grade in breast cancer is described as G...,Grade describes how abnormal the tumor cells l...,Tumor grade in breast cancer is clinically sig...,Cancer grades describe how quickly cancers gro...,6771.0
1894,Medical-4dc06fbd,Medical,What are the most common therapies used in the...,Systemic therapies for breast cancer include c...,Contextual Summarize,Systemic therapies for breast cancer include c...,Systemic therapy is used for invasive and meta...,The most common systemic therapies used in bre...,Most types of radiation include several short ...,13941.0
1895,Medical-19f19b9b,Medical,How are imaging and biopsy utilized throughout...,Imaging and biopsy play critical roles through...,Contextual Summarize,Imaging is used for screening breast cancer.; ...,Screening mammograms are used for early detect...,Imaging is utilized for **screening** through ...,Imaging techniques are utilized to determine t...,23189.0

In [6]:
try:
    medical_questions_evaluated = pd.read_parquet("data/evaluations/contextual_summarization_evaluated.parquet")
    medical_questions_evaluated = (
        medical_questions_evaluated
        .set_index("qid")
        .to_dict(orient="index")
    )
except:
    medical_questions_evaluated = {}


medical_questions_evaluated

{'Medical-5fd3c02d': {'accuracy': 0.8975624233072602,
  'coverage': 0.8,
  'tokens': 12639},
 'Medical-b8b22d33': {'accuracy': 0.799239873834546,
  'coverage': 0.6666666666666666,
  'tokens': 6866},
 'Medical-9c85110b': {'accuracy': 0.856498707381742,
  'coverage': 0.7857142857142857,
  'tokens': 10808}}

In [7]:
def all_valid(values):
    return all(
        v is not None and not np.isnan(v)
        for v in values
    )

In [8]:
#accuracy
#coverage

from tqdm import tqdm
import time
sep = "\n\n" + "-"*100 + "\n\n"
MAX_RETRIES = 10
SLEEP_SEC = 30

def get_answers():
    for qid in tqdm(question_ids):
        if qid in medical_questions_evaluated:
            continue

        row = relevant_questions.loc[relevant_questions["id"] == qid].iloc[0]
        row_eval = {}

        question = row["question"]
        reference = row["answer"]
        answer = row["LLM_answer"]
        context = row["LLM_context"]
        contexts = context.split(sep)
        
        accuracy, token1 = None, None
        for attempt in range(1, MAX_RETRIES + 1):
            try:
                accuracy, token1 = compute_answer_accuracy(question, answer, reference, call_gemini, create_embedding)
                break
            except Exception as e:
                code = e.error.code if hasattr(e, "error") else e
                print(f"[ERROR] qid={qid} accuracy calculation failed after {attempt} retries: {code}")
                if attempt == MAX_RETRIES:
                    return
                time.sleep(SLEEP_SEC * attempt)  #backoff

        coverage, token2 = None, None
        for attempt in range(1, MAX_RETRIES + 1):
            try:
                coverage, token2 = compute_coverage(question, reference, answer, call_gemini)
                break
            except Exception as e:
                code = e.error.code if hasattr(e, "error") else e
                print(f"[ERROR] qid={qid} coverage calculation failed after {attempt} retries: {code}")
                if attempt == MAX_RETRIES:
                    return
                time.sleep(SLEEP_SEC * attempt)  #backoff
        if all_valid([accuracy, coverage, token1, token2]):
            row_eval["accuracy"] = accuracy
            row_eval["coverage"] = coverage
            row_eval["tokens"] = token1 + token2
            medical_questions_evaluated[qid] = row_eval
get_answers()

100%|██████████| 289/289 [3:43:00<00:00, 46.30s/it]

In [9]:
medical_questions_evaluated

{'Medical-5fd3c02d': {'accuracy': 0.8975624233072602,
  'coverage': 0.8,
  'tokens': 12639},
 'Medical-b8b22d33': {'accuracy': 0.799239873834546,
  'coverage': 0.6666666666666666,
  'tokens': 6866},
 'Medical-9c85110b': {'accuracy': 0.856498707381742,
  'coverage': 0.7857142857142857,
  'tokens': 10808},
 'Medical-fcf87025': {'accuracy': 0.6135058700694611,
  'coverage': 0.8,
  'tokens': 9777},
 'Medical-6baf8bff': {'accuracy': 0.6305920222156903,
  'coverage': 0.21052631578947367,
  'tokens': 10218},
 'Medical-643b2b9d': {'accuracy': 0.6099826097019654,
  'coverage': 1.0,
  'tokens': 7927},
 'Medical-25f8ca5e': {'accuracy': 0.5365685104843791,
  'coverage': 0.5,
  'tokens': 6797},
 'Medical-d961b796': {'accuracy': 0.7094433605243194,
  'coverage': 0.8,
  'tokens': 10810},
 'Medical-915df475': {'accuracy': 0.7335145324028612,
  'coverage': 0.625,
  'tokens': 12166},
 'Medical-e0e8fd6d': {'accuracy': 0.8427452802240482,
  'coverage': 0.8571428571428571,
  'tokens': 9904},
 'Medical-d7012112': {'accuracy': 0.7425224184596595,
  'coverage': 0.6363636363636364,
  'tokens': 20399},
 'Medical-6bb8a85b': {'accuracy': 0.9198582969911755,
  'coverage': 1.0,
  'tokens': 12694},
 'Medical-0a87d395': {'accuracy': 0.6254960230073308,
  'coverage': 0.5833333333333334,
  'tokens': 10964},
 'Medical-23285edf': {'accuracy': 0.7384761124404875,
  'coverage': 1.0,
  'tokens': 6190},
 'Medical-a1adaecd': {'accuracy': 0.5093683169593821,
  'coverage': 0.21739130434782608,
  'tokens': 16695},
 'Medical-ead123bc': {'accuracy': 0.6125785112052856,
  'coverage': 0.6923076923076923,
  'tokens': 9345},
 'Medical-ce5815bf': {'accuracy': 0.6373991694905166,
  'coverage': 0.5555555555555556,
  'tokens': 12349},
 'Medical-17444c2c': {'accuracy': 0.7744833091196599,
  'coverage': 0.5238095238095238,
  'tokens': 13742},
 'Medical-9e04431e': {'accuracy': 0.944611100729187,
  'coverage': 1.0,
  'tokens': 11648},
 'Medical-0170eecb': {'accuracy': 0.6409207311122064,
  'coverage': 0.7142857142857143,
  'tokens': 10831},
 'Medical-79b30aaa': {'accuracy': 0.7584329706221186,
  'coverage': 0.64,
  'tokens': 17370},
 'Medical-76e69cd5': {'accuracy': 0.784363775048279,
  'coverage': 0.7142857142857143,
  'tokens': 12932},
 'Medical-ff793656': {'accuracy': 0.43823264670801937,
  'coverage': 0.9,
  'tokens': 10945},
 'Medical-62d1fdf9': {'accuracy': 0.6513959631509467,
  'coverage': 0.3888888888888889,
  'tokens': 18787},
 'Medical-fd3d70cc': {'accuracy': 0.5709305655262669,
  'coverage': 0.2777777777777778,
  'tokens': 15183},
 'Medical-1b9a995e': {'accuracy': 0.8045283853492097,
  'coverage': 1.0,
  'tokens': 4742},
 'Medical-7544e6ca': {'accuracy': 0.4452395939534165,
  'coverage': 0.14285714285714285,
  'tokens': 16288},
 'Medical-aae429f4': {'accuracy': 0.8390213608246759,
  'coverage': 1.0,
  'tokens': 10231},
 'Medical-d21811b0': {'accuracy': 0.5615463597081867,
  'coverage': 0.3333333333333333,
  'tokens': 11533},
 'Medical-61d081d5': {'accuracy': 0.6038396358044678,
  'coverage': 1.0,
  'tokens': 6298},
 'Medical-2952a7a6': {'accuracy': 0.8227129180804799,
  'coverage': 0.7777777777777778,
  'tokens': 9818},
 'Medical-0a7d95fc': {'accuracy': 0.5495089334710684,
  'coverage': 0.6,
  'tokens': 8810},
 'Medical-f8dc595c': {'accuracy': 0.8759414340301704,
  'coverage': 1.0,
  'tokens': 10567},
 'Medical-48edb564': {'accuracy': 0.6753764450162059,
  'coverage': 0.5714285714285714,
  'tokens': 14234},
 'Medical-b55db5c0': {'accuracy': 0.8965371548678314,
  'coverage': 1.0,
  'tokens': 10446},
 'Medical-024ef7a1': {'accuracy': 0.9915388523969818,
  'coverage': 1.0,
  'tokens': 4668},
 'Medical-c0c6b4fb': {'accuracy': 0.8478529810515457,
  'coverage': 0.7058823529411765,
  'tokens': 16217},
 'Medical-3cd90d08': {'accuracy': 0.2286079376935959,
  'coverage': 0.5,
  'tokens': 7744},
 'Medical-024819a8': {'accuracy': 0.9825279712255128,
  'coverage': 1.0,
  'tokens': 9285},
 'Medical-3cc76c04': {'accuracy': 0.21056970953941345,
  'coverage': 0.0,
  'tokens': 10537},
 'Medical-df2fbbd7': {'accuracy': 0.23855647444725037,
  'coverage': 0.6363636363636364,
  'tokens': 12373},
 'Medical-2fcaf5ff': {'accuracy': 0.6933877742781456,
  'coverage': 0.5555555555555556,
  'tokens': 8605},
 'Medical-bbb1e0c6': {'accuracy': 0.21758562326431274,
  'coverage': 0.0,
  'tokens': 5575},
 'Medical-31427bc6': {'accuracy': 0.698595804619426,
  'coverage': 0.75,
  'tokens': 8187},
 'Medical-0c1ef334': {'accuracy': 0.8244314619073176,
  'coverage': 0.6,
  'tokens': 12726},
 'Medical-611836a0': {'accuracy': 0.5307931184435344,
  'coverage': 0.6666666666666666,
  'tokens': 8711},
 'Medical-e168b4d3': {'accuracy': 0.34999322888943685,
  'coverage': 0.375,
  'tokens': 9726},
 'Medical-9f34bb0a': {'accuracy': 0.7580316232848346,
  'coverage': 0.5,
  'tokens': 8308},
 'Medical-69e0dbc6': {'accuracy': 0.7317317127781457,
  'coverage': 0.6,
  'tokens': 11318},
 'Medical-6c6ace8b': {'accuracy': 0.6752361929943118,
  'coverage': 0.6666666666666666,
  'tokens': 7387},
 'Medical-7b4b0aa6': {'accuracy': 0.5578578320460572,
  'coverage': 0.2,
  'tokens': 10520},
 'Medical-9712745d': {'accuracy': 0.8161610261332677,
  'coverage': 0.8571428571428571,
  'tokens': 10169},
 'Medical-0ae62420': {'accuracy': 0.37997474666576825,
  'coverage': 0.38461538461538464,
  'tokens': 12404},
 'Medical-35e77a1a': {'accuracy': 0.3638502372018868,
  'coverage': 0.14285714285714285,
  'tokens': 11420},
 'Medical-97ddb491': {'accuracy': 0.8721291507572507,
  'coverage': 0.7142857142857143,
  'tokens': 9659},
 'Medical-fe85502c': {'accuracy': 0.7194612133104559,
  'coverage': 0.4444444444444444,
  'tokens': 15943},
 'Medical-8644244f': {'accuracy': 0.8533932715241288,
  'coverage': 0.8125,
  'tokens': 13374},
 'Medical-c2a36052': {'accuracy': 0.7938411877243963,
  'coverage': 0.6666666666666666,
  'tokens': 8606},
 'Medical-8cb461ed': {'accuracy': 0.6567913988846394,
  'coverage': 0.5,
  'tokens': 17078},
 'Medical-60b3092a': {'accuracy': 0.7985266893586472,
  'coverage': 0.6666666666666666,
  'tokens': 4632},
 'Medical-83b86188': {'accuracy': 0.4359450161190395,
  'coverage': 0.4117647058823529,
  'tokens': 12462},
 'Medical-01f95b27': {'accuracy': 0.987176775869812,
  'coverage': 1.0,
  'tokens': 8479},
 'Medical-67b7cadd': {'accuracy': 0.8064272999361303,
  'coverage': 0.631578947368421,
  'tokens': 21243},
 'Medical-18b6cbc6': {'accuracy': 0.4888377785224345,
  'coverage': 0.3333333333333333,
  'tokens': 4903},
 'Medical-296c7595': {'accuracy': 0.841873800711422,
  'coverage': 0.6666666666666666,
  'tokens': 8867},
 'Medical-e8019816': {'accuracy': 0.8773220587455496,
  'coverage': 1.0,
  'tokens': 13175},
 'Medical-733f63f7': {'accuracy': 0.8071994482978729,
  'coverage': 1.0,
  'tokens': 9282},
 'Medical-2ab4a26d': {'accuracy': 0.5483700758125272,
  'coverage': 0.8,
  'tokens': 10768},
 'Medical-78a99b6b': {'accuracy': 0.9115342741166939,
  'coverage': 1.0,
  'tokens': 6021},
 'Medical-d6d07c2c': {'accuracy': 0.6781910776686979,
  'coverage': 0.75,
  'tokens': 7811},
 'Medical-d90aa96f': {'accuracy': 0.922417143479525,
  'coverage': 0.4444444444444444,
  'tokens': 6693},
 'Medical-b7a4ed28': {'accuracy': 0.8083872542469945,
  'coverage': 0.75,
  'tokens': 6884},
 'Medical-b5a3c96e': {'accuracy': 0.8872525691534912,
  'coverage': 0.8333333333333334,
  'tokens': 7546},
 'Medical-bcf1ff5a': {'accuracy': 0.7043134248783145,
  'coverage': 0.5,
  'tokens': 6023},
 'Medical-b1ec8b7e': {'accuracy': 0.7884433702592364,
  'coverage': 0.7,
  'tokens': 9827},
 'Medical-f24f442f': {'accuracy': 0.43848992667611886,
  'coverage': 0.8,
  'tokens': 7306},
 'Medical-e14162c2': {'accuracy': 0.6687495516450647,
  'coverage': 0.6,
  'tokens': 7556},
 'Medical-46ec9d7b': {'accuracy': 0.9064095417238734,
  'coverage': 0.8333333333333334,
  'tokens': 9657},
 'Medical-1565017b': {'accuracy': 0.7930035921871458,
  'coverage': 1.0,
  'tokens': 15707},
 'Medical-51a4d6d2': {'accuracy': 0.74222692843363,
  'coverage': 0.6666666666666666,
  'tokens': 14253},
 'Medical-f9a73f1e': {'accuracy': 0.5459686368326238,
  'coverage': 0.7142857142857143,
  'tokens': 12460},
 'Medical-b08051d8': {'accuracy': 0.6496539738682626,
  'coverage': 0.3,
  'tokens': 13319},
 'Medical-5df1a831': {'accuracy': 0.574900498714392,
  'coverage': 0.0,
  'tokens': 8585},
 'Medical-5779b132': {'accuracy': 0.6318913109602098,
  'coverage': 0.8571428571428571,
  'tokens': 13138},
 'Medical-dfb56ae9': {'accuracy': 0.7497946522403355,
  'coverage': 1.0,
  'tokens': 9577},
 'Medical-37ade7a5': {'accuracy': 0.6712863700326761,
  'coverage': 0.35714285714285715,
  'tokens': 13901},
 'Medical-0a9237ce': {'accuracy': 0.6057654212524093,
  'coverage': 0.23076923076923078,
  'tokens': 13205},
 'Medical-50c09918': {'accuracy': 0.6983711994185264,
  'coverage': 1.0,
  'tokens': 11643},
 'Medical-62476085': {'accuracy': 0.5888555851946932,
  'coverage': 0.375,
  'tokens': 8063},
 'Medical-5cb17774': {'accuracy': 0.9890265166196991,
  'coverage': 0.6666666666666666,
  'tokens': 6796},
 'Medical-1d7e42b7': {'accuracy': 0.5834672060923829,
  'coverage': 0.6666666666666666,
  'tokens': 9458},
 'Medical-0b161de9': {'accuracy': 0.6110738515385132,
  'coverage': 1.0,
  'tokens': 5995},
 'Medical-0dd275c6': {'accuracy': 0.8442363808700797,
  'coverage': 0.8333333333333334,
  'tokens': 9037},
 'Medical-3c38602c': {'accuracy': 0.5906896499061034,
  'coverage': 1.0,
  'tokens': 6586},
 'Medical-5ba676fd': {'accuracy': 0.8023803829760071,
  'coverage': 0.8,
  'tokens': 13932},
 'Medical-20eb3bc8': {'accuracy': 0.6563057402353057,
  'coverage': 0.8,
  'tokens': 9916},
 'Medical-3b99f5cd': {'accuracy': 0.8615737705954056,
  'coverage': 1.0,
  'tokens': 7950},
 'Medical-ec4330ad': {'accuracy': 0.7266166209693079,
  'coverage': 0.7142857142857143,
  'tokens': 8763},
 'Medical-a8a154f8': {'accuracy': 0.5869195071257616,
  'coverage': 0.34782608695652173,
  'tokens': 11090},
 'Medical-f04a4100': {'accuracy': 0.44334403955122414,
  'coverage': 0.5,
  'tokens': 14025},
 'Medical-f38ec745': {'accuracy': 0.775989519660014,
  'coverage': 1.0,
  'tokens': 7477},
 'Medical-0bc96001': {'accuracy': 0.7440993189410041,
  'coverage': 0.75,
  'tokens': 13320},
 'Medical-d1ead1ea': {'accuracy': 0.8621516823299866,
  'coverage': 0.6666666666666666,
  'tokens': 8102},
 'Medical-cd32265c': {'accuracy': 0.21431803703308105,
  'coverage': 0.0,
  'tokens': 8971},
 'Medical-363f6824': {'accuracy': 0.8430897950717765,
  'coverage': 0.5625,
  'tokens': 13137},
 'Medical-da6253bc': {'accuracy': 0.7627856121350762,
  'coverage': 0.8333333333333334,
  'tokens': 7669},
 'Medical-61c0e9bc': {'accuracy': 0.42917256053590547,
  'coverage': 0.4166666666666667,
  'tokens': 17000},
 'Medical-bc92c071': {'accuracy': 0.663579161641307,
  'coverage': 1.0,
  'tokens': 11442},
 'Medical-8897e674': {'accuracy': 0.8148449853747335,
  'coverage': 0.75,
  'tokens': 6043},
 'Medical-6e7c77a8': {'accuracy': 0.7431639581537764,
  'coverage': 0.5555555555555556,
  'tokens': 8826},
 'Medical-0fd3dcfd': {'accuracy': 0.734598010730279,
  'coverage': 0.6666666666666666,
  'tokens': 5747},
 'Medical-c39fbc42': {'accuracy': 0.7381943761802399,
  'coverage': 0.6666666666666666,
  'tokens': 5871},
 'Medical-5161f780': {'accuracy': 0.9956524967397278,
  'coverage': 1.0,
  'tokens': 2650},
 'Medical-2a12c6b8': {'accuracy': 0.7268337449208371,
  'coverage': 0.7333333333333333,
  'tokens': 15091},
 'Medical-4357e2e4': {'accuracy': 0.7402995973425455,
  'coverage': 0.3333333333333333,
  'tokens': 10122},
 'Medical-3dea6ece': {'accuracy': 0.8292295246836361,
  'coverage': 1.0,
  'tokens': 8116},
 'Medical-06ba718a': {'accuracy': 0.6173865049698689,
  'coverage': 0.16666666666666666,
  'tokens': 12028},
 'Medical-c01491e4': {'accuracy': 0.5469602048061126,
  'coverage': 0.35714285714285715,
  'tokens': 11057},
 'Medical-64c2bdbe': {'accuracy': 0.7170353638717823,
  'coverage': 0.5,
  'tokens': 15380},
 'Medical-d76e4df9': {'accuracy': 0.5895678312924233,
  'coverage': 0.3333333333333333,
  'tokens': 10919},
 'Medical-0fe6af86': {'accuracy': 0.7654426854010926,
  'coverage': 0.5217391304347826,
  'tokens': 19720},
 'Medical-6c832349': {'accuracy': 0.6914973675822181,
  'coverage': 0.5,
  'tokens': 17144},
 'Medical-0dc6b940': {'accuracy': 0.5397814243630656,
  'coverage': 0.7272727272727273,
  'tokens': 12214},
 'Medical-31dd8ffb': {'accuracy': 0.5591369325098031,
  'coverage': 0.4375,
  'tokens': 12901},
 'Medical-8d17a0a2': {'accuracy': 0.6606115829551011,
  'coverage': 0.4444444444444444,
  'tokens': 14491},
 'Medical-0002d2de': {'accuracy': 0.8004418014987854,
  'coverage': 1.0,
  'tokens': 6033},
 'Medical-6da13b57': {'accuracy': 0.5119252681398845,
  'coverage': 0.0,
  'tokens': 13942},
 'Medical-3e66af03': {'accuracy': 0.2153262197971344,
  'coverage': 0.0,
  'tokens': 8734},
 'Medical-5f6b723d': {'accuracy': 0.6271398156494665,
  'coverage': 0.5714285714285714,
  'tokens': 8576},
 'Medical-d72543ef': {'accuracy': 0.6873642175984693,
  'coverage': 1.0,
  'tokens': 9047},
 'Medical-ee0d07fe': {'accuracy': 0.8150304005234685,
  'coverage': 0.75,
  'tokens': 6041},
 'Medical-880d8f25': {'accuracy': 0.5437503580121813,
  'coverage': 0.2222222222222222,
  'tokens': 12959},
 'Medical-2a43b505': {'accuracy': 0.5908212871737499,
  'coverage': 0.25,
  'tokens': 16702},
 'Medical-181fe114': {'accuracy': 0.7368243336229634,
  'coverage': 0.8,
  'tokens': 5833},
 'Medical-251615ea': {'accuracy': 0.9936675726898652,
  'coverage': 1.0,
  'tokens': 5528},
 'Medical-1e74344c': {'accuracy': 0.5061021514517559,
  'coverage': 0.5,
  'tokens': 12670},
 'Medical-69c5e22f': {'accuracy': 0.36185103781147543,
  'coverage': 0.0,
  'tokens': 12077},
 'Medical-61a5ec94': {'accuracy': 0.6980305200624777,
  'coverage': 0.3888888888888889,
  'tokens': 14744},
 'Medical-088c7ad0': {'accuracy': 0.6214499290512799,
  'coverage': 0.4166666666666667,
  'tokens': 12802},
 'Medical-b17a5c65': {'accuracy': 0.7308680116685835,
  'coverage': 0.5,
  'tokens': 8019},
 'Medical-c9e77dca': {'accuracy': 0.23871009051799774,
  'coverage': 1.0,
  'tokens': 4679},
 'Medical-eb6686a0': {'accuracy': 0.2362724244594574,
  'coverage': 0.7142857142857143,
  'tokens': 12134},
 'Medical-4641d74e': {'accuracy': 0.8886994187821189,
  'coverage': 1.0,
  'tokens': 8018},
 'Medical-9e6a8495': {'accuracy': 0.9514289471576248,
  'coverage': 1.0,
  'tokens': 6883},
 'Medical-6f917f07': {'accuracy': 0.6675580108472507,
  'coverage': 0.6666666666666666,
  'tokens': 8602},
 'Medical-6b047fee': {'accuracy': 0.49413177454941953,
  'coverage': 0.3333333333333333,
  'tokens': 9196},
 'Medical-a9f73379': {'accuracy': 0.7331739067616345,
  'coverage': 0.7142857142857143,
  'tokens': 8068},
 'Medical-77d91ba8': {'accuracy': 0.6460080699832681,
  'coverage': 0.16666666666666666,
  'tokens': 7560},
 'Medical-e1db913e': {'accuracy': 0.5679204364321369,
  'coverage': 0.46153846153846156,
  'tokens': 9464},
 'Medical-05f3bf13': {'accuracy': 0.8190275007275911,
  'coverage': 0.5555555555555556,
  'tokens': 11475},
 'Medical-2148aacc': {'accuracy': 0.793434384852761,
  'coverage': 0.5833333333333334,
  'tokens': 11901},
 'Medical-5905da7e': {'accuracy': 0.23400428891181946,
  'coverage': 0.75,
  'tokens': 6130},
 'Medical-74be0fed': {'accuracy': 0.6786719732774427,
  'coverage': 0.5,
  'tokens': 15917},
 'Medical-1991db28': {'accuracy': 0.5975399016888672,
  'coverage': 0.0,
  'tokens': 7626},
 'Medical-f3cb62dc': {'accuracy': 0.792428687163289,
  'coverage': 0.8333333333333334,
  'tokens': 8317},
 'Medical-8171339b': {'accuracy': 0.6046613752414867,
  'coverage': 1.0,
  'tokens': 6360},
 'Medical-c1c8e6d9': {'accuracy': 0.4660231608220354,
  'coverage': 0.6666666666666666,
  'tokens': 6818},
 'Medical-a7769409': {'accuracy': 0.5317893504816436,
  'coverage': 0.2,
  'tokens': 7938},
 'Medical-25f9adbb': {'accuracy': 0.6021738493940055,
  'coverage': 0.3333333333333333,
  'tokens': 16335},
 'Medical-0d99173e': {'accuracy': 0.5796361182015828,
  'coverage': 0.5,
  'tokens': 14846},
 'Medical-18c0b2dd': {'accuracy': 0.7207520896962907,
  'coverage': 0.2222222222222222,
  'tokens': 14198},
 'Medical-27277239': {'accuracy': 0.8520147423097846,
  'coverage': 1.0,
  'tokens': 7066},
 'Medical-192138ad': {'accuracy': 0.5959242879991891,
  'coverage': 0.0,
  'tokens': 12175},
 'Medical-7099cc9f': {'accuracy': 0.5368460714426422,
  'coverage': 0.2,
  'tokens': 13937},
 'Medical-dcbc35dd': {'accuracy': 0.5751826677636236,
  'coverage': 0.0,
  'tokens': 10413},
 'Medical-7d2a19f6': {'accuracy': 0.5938354642640771,
  'coverage': 0.5555555555555556,
  'tokens': 10868},
 'Medical-3276a6de': {'accuracy': 0.7594611065793216,
  'coverage': 0.5,
  'tokens': 7698},
 'Medical-03a82e56': {'accuracy': 0.36128157504152947,
  'coverage': 0.5,
  'tokens': 8968},
 'Medical-8e6563e6': {'accuracy': 0.6944302947569145,
  'coverage': 0.39285714285714285,
  'tokens': 24404},
 'Medical-a3c885aa': {'accuracy': 0.7285048216039678,
  'coverage': 0.4,
  'tokens': 7845},
 'Medical-14de13d0': {'accuracy': 0.560973692160895,
  'coverage': 0.5,
  'tokens': 11149},
 'Medical-fb67edf6': {'accuracy': 0.7387779950698887,
  'coverage': 0.375,
  'tokens': 13281},
 'Medical-28687496': {'accuracy': 0.6528212676028976,
  'coverage': 0.7142857142857143,
  'tokens': 9907},
 'Medical-9601f6f1': {'accuracy': 0.4361797441374422,
  'coverage': 0.3333333333333333,
  'tokens': 14126},
 'Medical-19aa2257': {'accuracy': 0.8404175698337171,
  'coverage': 0.4444444444444444,
  'tokens': 7753},
 'Medical-ee34cda2': {'accuracy': 0.44310970387260257,
  'coverage': 0.5,
  'tokens': 7750},
 'Medical-fc7727b2': {'accuracy': 0.8224499912497168,
  'coverage': 0.7,
  'tokens': 17905},
 'Medical-403bb394': {'accuracy': 0.711442921464349,
  'coverage': 0.5,
  'tokens': 7689},
 'Medical-b9f1cbe3': {'accuracy': 0.4834270833119227,
  'coverage': 0.35294117647058826,
  'tokens': 17236},
 'Medical-0d661e08': {'accuracy': 0.8632672215775673,
  'coverage': 0.5,
  'tokens': 7702},
 'Medical-2c03807c': {'accuracy': 0.5368866502869079,
  'coverage': 0.4375,
  'tokens': 13744},
 'Medical-d33066da': {'accuracy': 0.5733801332377837,
  'coverage': 0.5555555555555556,
  'tokens': 12474},
 'Medical-0895dc9d': {'accuracy': 0.760644519289696,
  'coverage': 0.6428571428571429,
  'tokens': 9410},
 'Medical-aa179e3f': {'accuracy': 0.21947965025901794,
  'coverage': 0.0,
  'tokens': 6188},
 'Medical-d94fa48e': {'accuracy': 0.7359110116536849,
  'coverage': 0.21428571428571427,
  'tokens': 15169},
 'Medical-18e51427': {'accuracy': 0.6873397945941477,
  'coverage': 0.625,
  'tokens': 9380},
 'Medical-bf479234': {'accuracy': 0.7355546652729055,
  'coverage': 0.6666666666666666,
  'tokens': 6168},
 'Medical-67d6c501': {'accuracy': 0.7406772672761838,
  'coverage': 0.625,
  'tokens': 14748},
 'Medical-aa279376': {'accuracy': 0.7818736752872528,
  'coverage': 0.7,
  'tokens': 10041},
 'Medical-a3c71579': {'accuracy': 0.8781792606190865,
  'coverage': 0.6,
  'tokens': 7877},
 'Medical-6809b810': {'accuracy': 0.5937976304572514,
  'coverage': 0.3333333333333333,
  'tokens': 11999},
 'Medical-3cf18099': {'accuracy': 0.5699398425483153,
  'coverage': 0.3333333333333333,
  'tokens': 5475},
 'Medical-c2dcacec': {'accuracy': 0.7016892915816509,
  'coverage': 0.29411764705882354,
  'tokens': 13333},
 'Medical-f657d12f': {'accuracy': 0.6007741093208476,
  'coverage': 0.8,
  'tokens': 8993},
 'Medical-ee0525ef': {'accuracy': 0.41004879272994776,
  'coverage': 0.8,
  'tokens': 9537},
 'Medical-2cb951c9': {'accuracy': 0.8447629272337775,
  'coverage': 1.0,
  'tokens': 6687},
 'Medical-84f32cc1': {'accuracy': 0.7964442222794846,
  'coverage': 0.6666666666666666,
  'tokens': 5693},
 'Medical-1edecc97': {'accuracy': 0.537979248128751,
  'coverage': 0.5,
  'tokens': 10442},
 'Medical-f23b49f6': {'accuracy': 0.7051606664108288,
  'coverage': 1.0,
  'tokens': 9108},
 'Medical-29e992c3': {'accuracy': 0.3752597659556279,
  'coverage': 0.25,
  'tokens': 7695},
 'Medical-aec58243': {'accuracy': 0.7749112567287435,
  'coverage': 0.6363636363636364,

In [10]:
df_eval = (
    pd.DataFrame.from_dict(medical_questions_evaluated, orient="index")
      .reset_index()
      .rename(columns={"index": "qid"})
)

In [11]:
df_eval.to_parquet("data/evaluations/contextual_summarization_evaluated.parquet")
df_eval_loaded = pd.read_parquet("data/evaluations/contextual_summarization_evaluated.parquet")
df_eval_loaded

                  qid  accuracy  coverage  tokens
0    Medical-5fd3c02d  0.897562  0.800000   12639
1    Medical-b8b22d33  0.799240  0.666667    6866
2    Medical-9c85110b  0.856499  0.785714   10808
3    Medical-fcf87025  0.613506  0.800000    9777
4    Medical-6baf8bff  0.630592  0.210526   10218
..                ...       ...       ...     ...
284  Medical-0cba5d0a  0.604894  0.583333   16398
285  Medical-d72d7cb9  0.400845  0.000000    6130
286  Medical-97d64c1f  0.863777  0.750000   11560
287  Medical-4dc06fbd  0.581375  0.666667    9562
288  Medical-19f19b9b  0.759075  0.833333   12072

[289 rows x 4 columns]

In [12]:
print("min:", df_eval_loaded["tokens"].min())
print("max:", df_eval_loaded["tokens"].max())
print("avg:", df_eval_loaded["tokens"].mean())
print("sum:", df_eval_loaded["tokens"].sum())

min: 2650
max: 24404
avg: 10683.259515570935
sum: 3087462

In [13]:
print("min:", df_eval_loaded["accuracy"].min())
print("max:", df_eval_loaded["accuracy"].max())
print("avg:", df_eval_loaded["accuracy"].mean())
print("sum:", df_eval_loaded["accuracy"].sum())

min: 0.21056970953941345
max: 0.9956524967397278
avg: 0.662963362888527
sum: 191.5964118747843

In [14]:
print("min:", df_eval_loaded["coverage"].min())
print("max:", df_eval_loaded["coverage"].max())
print("avg:", df_eval_loaded["coverage"].mean())
print("sum:", df_eval_loaded["coverage"].sum())

min: 0.0
max: 1.0
avg: 0.5918892969240213
sum: 171.05600681104215