# Notebook 1: Primary Graph Building

This notebook processes the cleaned text decomposition responses from the LLM, including semantic units, entities, and relationships, to build the corresponding **S**, **N**, and **R** nodes and link them. The default edge weight is 1. 

The resulting graph is called **G1 – the primary graph**. A mapping of entity names to node IDs is also stored for quick retrieval by entity matching. 

Finally, a NetworkX GML file is stored for visualization using Gephi or any other compatible tool.

In [1]:
import os
dir_path = os.getcwd()
print("The directory of this script is:", dir_path)
root_path = os.path.dirname(dir_path)
print("The root directory is:", root_path)

The directory of this script is: d:\Documents\GitHub\NodeRAG\graphs
The root directory is: d:\Documents\GitHub\NodeRAG

In [2]:
#load llm decomposition response
import pandas as pd
medical_responses = pd.read_parquet(f"{root_path}/text_decomposition/data/medical_responses_cleaned.parquet")
medical_responses

,index,response,cleaned_response,is_valid
0,0,"```json\n[\n {\n ""semantic_unit"": ""Basal c...","[\n {\n ""semantic_unit"": ""Basal cell skin ...",A valid decomposition response
1,1,"```json\n[\n {\n ""semantic_unit"": ""The hyp...","[\n {\n ""semantic_unit"": ""The hypodermis i...",A valid decomposition response
2,2,"```json\n[\n {\n ""semantic_unit"": ""Basal c...","[\n {\n ""semantic_unit"": ""Basal cell skin ...",A valid decomposition response
3,3,"```json\n[\n {\n ""semantic_unit"": ""Recurre...","[\n {\n ""semantic_unit"": ""Recurrence of ba...",A valid decomposition response
4,4,"```json\n[\n {\n ""semantic_unit"": ""This ch...","[\n {\n ""semantic_unit"": ""This chapter pro...",A valid decomposition response
...,...,...,...,...
549,549,"```json\n[\n {\n ""semantic_unit"": ""The pat...","[\n {\n ""semantic_unit"": ""The patient asks...",A valid decomposition response
550,550,"```json\n[\n {\n ""semantic_unit"": ""Questio...","[\n {\n ""semantic_unit"": ""Questions regard...",A valid decomposition response
551,551,"```json\n[\n {\n ""semantic_unit"": ""This un...","[\n {\n ""semantic_unit"": ""This unit addres...",A valid decomposition response
552,552,"```json\n[\n {\n ""semantic_unit"": ""This un...","[\n {\n ""semantic_unit"": ""This unit poses ...",A valid decomposition response
553,553,"```json\n[\n {\n ""semantic_unit"": ""A clini...","[\n {\n ""semantic_unit"": ""A clinical trial...",A valid decomposition response

In [3]:
#load Node class definition
import sys
sys.path.append(root_path)
from graphs.Node import Node

In [4]:
#regex for matching entities in relationship triples (only match whole word)
import re
def entities_in_relationship(rel, entities):
    rel_text = rel.content.lower()
    found = []
    for e in entities:
        pattern = r'\b' + re.escape(e.content.lower()) + r'\b'
        if re.search(pattern, rel_text):
            found.append(e)
    return found

In [5]:
#function for creating and linking S, N, R nodes
import json
from tqdm import tqdm
def build_nodes(df, source_name):
    nodes = dict()
    entity_nodes = dict()
    for idx in tqdm(range(len(df))):
        row = df.iloc[idx]
        response = row["cleaned_response"]
        response = json.loads(response)
        for unit_idx,unit in enumerate(response):
            #data
            semantic_unit = unit["semantic_unit"]
            entities = unit["entities"]
            relationships = unit["relationships"]

            #ids
            source_id = f"{source_name}-{idx}"
            semantic_id = f"{source_id}-S-{unit_idx}"
            #entities_ids = [f"{semantic_id}-N-{e_idx}" for e_idx in range(len(entities))]
            relationships_ids = [f"{semantic_id}-R-{r_idx}" for r_idx in range(len(relationships))]

            #create semantic node
            semantic_node = Node(
                id=semantic_id,
                node_type = "S",
                source = source_id,
                content = semantic_unit
            )

            #create entity nodes
            current_entity_nodes = set()
            for e_idx, entity in enumerate(entities):
                key = entity.strip().upper()
                if key not in entity_nodes:
                    entity_node = Node(
                        id = f"{source_name}-N-{len(entity_nodes)}",
                        node_type = "N",
                        source = "",
                        content = key
                    )
                    entity_nodes[key] = entity_node
                else:
                    entity_node = entity_nodes[key]
                current_entity_nodes.add(entity_node)

            #create relationship nodes
            relationship_nodes = []
            for r_idx, relationship in enumerate(relationships):
                relationship_node = Node(
                    id = relationships_ids[r_idx],
                    node_type = "R",
                    source = source_id,
                    content = relationship
                )
                relationship_nodes.append(relationship_node)

            #link nodes
            for entity_node in current_entity_nodes:
                semantic_node.link(entity_node)
                entity_node.link(semantic_node)
            
            for relationship_node in relationship_nodes:
                ents = entities_in_relationship(relationship_node, current_entity_nodes)
                for ent in ents:
                    relationship_node.link(ent)
                    ent.link(relationship_node)
            
            current_nodes = [semantic_node] + relationship_nodes
            for n in current_nodes:
                nodes[n.id] = n
    nodes.update({v.id: v for v in entity_nodes.values()})
    #store entities
    entities_dict = {k: v.id for k, v in entity_nodes.items()}
    return nodes, entities_dict

In [6]:
medical_nodes, medical_entities = build_nodes(medical_responses, "medical")

100%|██████████| 554/554 [00:01<00:00, 279.66it/s]

In [7]:
import pickle
with open(f"{root_path}/graphs/data/graphs/G1_medical_primary_graph.pkl", "wb") as f:
    pickle.dump(medical_nodes, f)
with open(f"{root_path}/graphs/data/nodes/entity/medical_entities.pkl", "wb") as f:
    pickle.dump(medical_entities, f)

In [8]:
with open(f"{root_path}/graphs/data/graphs/G1_medical_primary_graph.pkl", "rb") as f:
    medical_nodes = pickle.load(f)
with open(f"{root_path}/graphs/data/nodes/entity/medical_entities.pkl", "rb") as f:
    medical_entities = pickle.load(f)

In [9]:
#sanity checks
for node_id in medical_nodes:
    node = medical_nodes[node_id]
    for edge in node.edges:
        if node.edges[edge] > 1:
            print(node_id,"-",edge,"-",node.edges[edge])

In [10]:
def nodes_to_dataframe(nodes):
    data = []
    for node in nodes.values():
        data.append({
            "id": node.id,
            "node_type": node.node_type,
            "source": node.source,
            "content": node.content,
            "edges": node.edges
        })
    return pd.DataFrame(data)

medical_nodes_df = nodes_to_dataframe(medical_nodes)
medical_nodes_df = medical_nodes_df.sort_values(by=["source", "node_type", "id"]).reset_index(drop=True)
medical_nodes_df

,id,node_type,source,content,edges
0,medical-N-0,N,,BASAL CELL SKIN CANCER,"{'medical-0-S-0': 1, 'medical-0-S-0-R-0': 1, '..."
1,medical-N-1,N,,BASAL CELL CARCINOMA (BCC),{'medical-0-S-0': 1}
2,medical-N-10,N,,HEAD,"{'medical-0-S-1': 1, 'medical-0-S-1-R-8': 1, '..."
3,medical-N-100,N,,PATIENT,"{'medical-2-S-1': 1, 'medical-2-S-1-R-6': 1, '..."
4,medical-N-1000,N,,THE COST OF TRANSPORTATION,"{'medical-32-S-2': 1, 'medical-32-S-2-R-4': 1,..."
...,...,...,...,...,...
41768,medical-99-S-3-R-9,R,medical-99,"LEVEL OF CREATININE IN BLOOD, tells how well, ...","{'medical-N-2535': 1, 'medical-N-402': 1, 'med..."
41769,medical-99-S-0,S,medical-99,It is important to inquire with family members...,"{'medical-N-565': 1, 'medical-N-312': 1, 'medi..."
41770,medical-99-S-1,S,medical-99,Blood tests are procedures that examine blood ...,"{'medical-N-592': 1, 'medical-N-262': 1, 'medi..."
41771,medical-99-S-2,S,medical-99,A Complete Blood Count (CBC) and differential ...,"{'medical-N-2499': 1, 'medical-N-2525': 1, 'me..."
41772,medical-99-S-3,S,medical-99,A Comprehensive Metabolic Panel (CMP) evaluate...,"{'medical-N-2169': 1, 'medical-N-2536': 1, 'me..."

In [11]:
medical_entities

{'BASAL CELL SKIN CANCER': 'medical-N-0',
 'BASAL CELL CARCINOMA (BCC)': 'medical-N-1',
 'SKIN CANCER': 'medical-N-2',
 '3 MILLION CASES': 'medical-N-3',
 'UNITED STATES': 'medical-N-4',
 'SURGERY': 'medical-N-5',
 'EPIDERMIS': 'medical-N-6',
 'DERMIS': 'medical-N-7',
 'BASAL CELLS': 'medical-N-8',
 'FACE': 'medical-N-9',
 'HEAD': 'medical-N-10',
 'NECK': 'medical-N-11',
 'ARMS': 'medical-N-12',
 'LEGS': 'medical-N-13',
 'TRUNK': 'medical-N-14',
 'SUN': 'medical-N-15',
 'BASAL CELL LESION': 'medical-N-16',
 'CHEEK': 'medical-N-17',
 'SKIN': 'medical-N-18',
 'BODY': 'medical-N-19',
 '20 SQUARE FEET': 'medical-N-20',
 'BARRIER': 'medical-N-21',
 'BACTERIA': 'medical-N-22',
 'CHEMICALS': 'medical-N-23',
 'BODY TEMPERATURE': 'medical-N-24',
 '3 LAYERS': 'medical-N-25',
 'WATERPROOF BARRIER': 'medical-N-26',
 'SKIN COLOR': 'medical-N-27',
 'MELANIN': 'medical-N-28',
 'CONNECTIVE TISSUE': 'medical-N-29',
 'BLOOD VESSELS': 'medical-N-30',
 'OIL AND SWEAT GLANDS': 'medical-N-31',
 'NERVES': 'medical-N-32',
 'HAIR FOLLICLES': 'medical-N-33',
 'HYPODERMIS': 'medical-N-34',
 'FAT': 'medical-N-35',
 'SKIN CANCERS': 'medical-N-36',
 '3 MAIN TYPES OF CELLS': 'medical-N-37',
 'SQUAMOUS CELLS': 'medical-N-38',
 'NEW CELLS': 'medical-N-39',
 'MELANOCYTES': 'medical-N-40',
 "SKIN'S SURFACE": 'medical-N-41',
 'ULTRAVIOLET (UV) RAYS': 'medical-N-42',
 'BOOK': 'medical-N-43',
 'SQUAMOUS CELL SKIN CANCER': 'medical-N-44',
 'MELANOMA': 'medical-N-45',
 'NCCN GUIDELINES FOR PATIENTS': 'medical-N-46',
 'NCCN.ORG/PATIENTGUIDELINES': 'medical-N-47',
 'NCCN PATIENT GUIDES FOR CANCER APP': 'medical-N-48',
 'LIGHTER SKIN': 'medical-N-49',
 'LIGHTER HAIR': 'medical-N-50',
 'LIGHTER EYES': 'medical-N-51',
 'LESIONS': 'medical-N-52',
 'FLAT, PALE OR YELLOW AREAS': 'medical-N-53',
 'SCAR': 'medical-N-54',
 'RED PATCHES': 'medical-N-55',
 'SMALL, PINK OR RED, SHINY BUMPS': 'medical-N-56',
 'BLUE AREAS': 'medical-N-57',
 'BROWN AREAS': 'medical-N-58',
 'BLACK AREAS': 'medical-N-59',
 'OPEN SORES': 'medical-N-60',
 'DARKER (BROWN AND BLACK) SKIN': 'medical-N-61',
 'BROWN OR GLOSSY BLACK BUMP': 'medical-N-62',
 'ROLLED BORDER': 'medical-N-63',
 'NORMAL MOLE': 'medical-N-64',
 'NEW, CHANGING, BLEEDING, OR UNUSUAL SKIN GROWTHS': 'medical-N-65',
 'EARLY DETECTION': 'medical-N-66',
 'CHAPTER 2': 'medical-N-67',
 'TESTING FOR BASAL CELL SKIN CANCER': 'medical-N-68',
 'UV RADIATION': 'medical-N-69',
 'TANNING BEDS': 'medical-N-70',
 'DNA': 'medical-N-71',
 'BASAL SKIN CELLS': 'medical-N-72',
 'CELLS': 'medical-N-73',
 'CERTAIN RISK FACTORS': 'medical-N-74',
 'CANCER': 'medical-N-75',
 'A RISK FACTOR': 'medical-N-76',
 'RISK FACTORS': 'medical-N-77',
 'FAIR SKIN': 'medical-N-78',
 'RED OR BLOND HAIR': 'medical-N-79',
 'LIGHT EYE COLOR': 'medical-N-80',
 'PEOPLE': 'medical-N-81',
 'LIGHTER-COLORED SKIN': 'medical-N-82',
 'SKIN PIGMENT': 'medical-N-83',
 "SUN'S HARMFUL UV RAYS": 'medical-N-84',
 'AGE': 'medical-N-85',
 'SUN EXPOSURE': 'medical-N-86',
 'TIME': 'medical-N-87',
 'YOUNGER PEOPLE': 'medical-N-88',
 'HISTORY OF SKIN CANCER': 'medical-N-89',
 'FAMILY': 'medical-N-90',
 'RADIATION THERAPY': 'medical-N-91',
 'RADIATION TREATMENT': 'medical-N-92',
 'IMMUNE SUPPRESSION': 'medical-N-93',
 'WEAKENED IMMUNE SYSTEMS': 'medical-N-94',
 'ORGAN TRANSPLANTS': 'medical-N-95',
 'AUTOIMMUNE DISEASES': 'medical-N-96',
 'EARLY TREATMENT': 'medical-N-97',
 'SYSTEMIC THERAPY': 'medical-N-98',
 'TREATMENT': 'medical-N-99',
 'PATIENT': 'medical-N-100',
 'FULL SKIN EXAMS': 'medical-N-101',
 'DOCTOR': 'medical-N-102',
 'AT LEAST ONCE A YEAR': 'medical-N-103',
 'PREVENTION': 'medical-N-104',
 'CHAPTER 4: TREATMENT BY RISK AND RECURRENCE': 'medical-N-105',
 'RECURRENCE': 'medical-N-106',
 'LYMPH NODES': 'medical-N-107',
 'DISTANT PARTS OF THE BODY': 'medical-N-108',
 'CHAPTER 3: TYPES OF TREATMENT': 'medical-N-109',
 'CARE': 'medical-N-110',
 'QUESTIONS': 'medical-N-111',
 'SHARED DECISIONS': 'medical-N-112',
 'CARE TEAM': 'medical-N-113',
 'AREA WHERE IT WAS ORIGINALLY FOUND': 'medical-N-114',
 'QUESTIONS TO ASK': 'medical-N-115',
 'CANCER CARE': 'medical-N-116',
 'PATIENTS': 'medical-N-117',
 'PROVIDERS': 'medical-N-118',
 'EXPERTS': 'medical-N-119',
 'CURRENT CARE RECOMMENDATIONS': 'medical-N-120',
 'LATEST RESEARCH': 'medical-N-121',
 'PRACTICES': 'medical-N-122',
 'LEADING CANCER CENTERS': 'medical-N-123',
 'EXPERT RECOMMENDATIONS': 'medical-N-124',
 'OUTCOMES': 'medical-N-125',
 'IMPORTANT DECISIONS': 'medical-N-126',
 'THIS CHAPTER ON TESTING': 'medical-N-127',
 'GENERAL HEALTH TESTS': 'medical-N-128',
 'BIOPSY': 'medical-N-129',
 'IMAGING': 'medical-N-130',
 'TREATMENT PLANNING': 'medical-N-131',
 'DIAGNOSIS': 'medical-N-132',
 'LESION': 'medical-N-133',
 'TESTING': 'medical-N-134',
 'CHAPTER': 'medical-N-135',
 'TESTS': 'medical-N-136',
 'CONCERNING LESION': 'medical-N-137',
 'YOUR DOCTOR': 'medical-N-138',
 'GUIDE': 'medical-N-139',
 'TREATMENT PLAN': 'medical-N-140',
 'MEANING': 'medical-N-141',
 'DETAILS': 'medical-N-142',
 'ADRENAL TUMORS': 'medical-N-143',
 'ADRENAL GLANDS': 'medical-N-144',
 'HORMONES': 'medical-N-145',
 'KIDNEY': 'medical-N-146',
 'ENDOCRINE SYSTEM': 'medical-N-147',
 'TISSUES': 'medical-N-148',
 'ORGANS': 'medical-N-149',
 'CHEMICAL SUBSTANCES': 'medical-N-150',
 'BLOODSTREAM': 'medical-N-151',
 'ADRENAL GLAND': 'medical-N-152',
 'ADRENAL CORTEX': 'medical-N-153',
 'ADRENAL MEDULLA': 'medical-N-154',
 'CORTISOL': 'medical-N-155',
 'ALDOSTERONE': 'medical-N-156',
 'DEHYDROEPIANDROSTERONE (DHEA)': 'medical-N-157',
 'METABOLISM': 'medical-N-158',
 'BLOOD PRESSURE': 'medical-N-159',
 'BODY FEATURES': 'medical-N-160',
 'HAIR GROWTH': 'medical-N-161',
 'BODY SHAPE': 'medical-N-162',
 'EPINEPHRINE': 'medical-N-163',
 'NOREPINEPHRINE': 'medical-N-164',
 'DOPAMINE': 'medical-N-165',
 "BODY'S RESPONSE TO STRESS": 'medical-N-166',
 'FIGHT OR FLIGHT SURGE OF ADRENALINE': 'medical-N-167',
 'KIDNEYS': 'medical-N-168',
 'IMMUNE SYSTEM': 'medical-N-169',
 'RESPONSE TO STRESS': 'medical-N-170',
 'OTHER FUNCTIONS': 'medical-N-171',
 'SYMPTOMS': 'medical-N-172',
 'IMAGING TEST': 'medical-N-173',
 'CT SCAN': 'medical-N-174',
 'MRI SCAN': 'medical-N-175',
 'BENIGN ADRENAL TUMORS': 'medical-N-176',
 'IMAGING TESTS': 'medical-N-177',
 'FUNCTIONAL ADRENAL TUMORS': 'medical-N-178',
 'HORMONE-RELATED SYMPTOMS': 'medical-N-179',
 'MALIGNANT ADRENAL TUMORS': 'medical-N-180',
 'CANCEROUS TUMORS': 'medical-N-181',
 '300 TO 500 PEOPLE': 'medical-N-182',
 'EACH YEAR': 'medical-N-183',
 'GENETIC CONDITIONS': 'medical-N-184',
 'RISK': 'medical-N-185',
 'ADRENOCORTICAL CARCINOMA': 'medical-N-186',
 'ACC': 'medical-N-187',
 'ADRENAL GLAND CANCER': 'medical-N-188',
 '1 TO 2 PEOPLE': 'medical-N-189',
 '1 MILLION': 'medical-N-190',
 'ANY AGE': 'medical-N-191',
 'CHILDREN AGES 5 AND UNDER': 'medical-N-192',
 'ADULTS IN THEIR 40S AND 50S': 'medical-N-193',
 'ADRENAL CANCER': 'medical-N-194',
 'PROGRESSION': 'medical-N-195',
 'NEUROBLASTOMA': 'medical-N-196',
 'ADRENAL TUMOR': 'medical-N-197',
 'CANCEROUS': 'medical-N-198',
 'INFANTS': 'medical-N-199',
 'BONES': 'medical-N-200',
 'PHEOCHROMOCYTOMA': 'medical-N-201',
 'TUMOR': 'medical-N-202',
 'HIGH BLOOD PRESSURE': 'medical-N-203',
 'HEADACHE': 'medical-N-204',
 'RAPID HEARTBEAT': 'medical-N-205',
 'SWEATING': 'medical-N-206',
 'BENIGN': 'medical-N-207',
 'ADENOMA': 'medical-N-208',
 'ADRENAL GLAND TUMOR': 'medical-N-209',
 'ADRENOCORTICAL ADENOMA': 'medical-N-210',
 'NONCANCEROUS TUMOR': 'medical-N-211',
 'STRESS HORMONE': 'medical-N-212',
 'CUSHING SYNDROME': 'medical-N-213',
 'ADRENAL TUMOR CATEGORIES': 'medical-N-214',
 'NEARBY ORGANS': 'medical-N-215',
 'HEALTH CARE PROVIDER': 'medical-N-216',
 'WEIGHT GAIN': 'medical-N-217',
 'MUSCLE WEAKNESS': 'medical-N-218',
 'PINK OR PURPLE STRETCH MARKS ON THE SKIN': 'medical-N-219',
 'HORMONAL CHANGES': 'medical-N-220',
 'EXCESS FACIAL HAIR': 'medical-N-221',
 'HAIR LOSS ON THE HEAD': 'medical-N-222',
 'IRREGULAR PERIODS': 'medical-N-223',
 'ENLARGED BREAST TISSUE': 'medical-N-224',
 'SHRINKING TESTICLES': 'medical-N-225',
 'NAUSEA': 'medical-N-226',
 'VOMITING': 'medical-N-227',
 'ABDOMINAL BLOATING': 'medical-N-228',
 'BACK PAIN': 'medical-N-229',
 'FEVER': 'medical-N-230',
 'LOSS OF APPETITE': 'medical-N-231',
 'LOSS OF WEIGHT WITHOUT TRYING': 'medical-N-232',
 'HEREDITARY CONDITIONS': 'medical-N-233',
 'MUTATIONS': 'medical-N-234',
 'BIOLOGICAL PARENT': 'medical-N-235',
 'CHILD': 'medical-N-236',
 'GENES': 'medical-N-237',
 'BECKWITH-WIEDEMANN SYNDROME': 'medical-N-238',
 'CARNEY COMPLEX': 'medical-N-239',
 'FAMILIAL ADENOMATOUS POLYPOSIS': 'medical-N-240',
 'FAP': 'medical-N-241',
 'HEREDITARY PARAGANGLIOMA-PHEOCHROMOCYTOMA SYNDROME': 'medical-N-242',
 'PGL/PCC SYNDROME': 'medical-N-243',
 'LI-FRAUMENI SYNDROME': 'medical-N-244',
 'LYNCH SYNDROME': 'medical-N-245',
 'MULTIPLE ENDOCRINE NEOPLASIA TYPE 1': 'medical-N-246',
 'MEN 1': 'medical-N-247',
 'MULTIPLE ENDOCRINE NEOPLASIA TYPE 2': 'medical-N-248',
 'MEN 2': 'medical-N-249',
 'NEUROFIBROMATOSIS TYPE 1': 'medical-N-250',
 'NF1': 'medical-N-251',
 'VON HIPPEL-LINDAU SYNDROME': 'medical-N-252',
 'VHL': 'medical-N-253',
 'KIDNEY TUMOR': 'medical-N-254',
 'NCCN GUIDELINES FOR PATIENTS: KIDNEY CANCER': 'medical-N-255',
 'NCCN': 'medical-N-256',
 'YELLOW GLANDS': 'medical-N-257',
 'TUMORS': 'medical-N-258',
 'RARE CANCER': 'medical-N-259',
 'ADRENOCORTICAL CANCER (ACC)': 'medical-N-260',
 'INCREASED RISK': 'medical-N-261',
 'BLOOD TESTS': 'medical-N-262',
 'GENETIC TESTS': 'medical-N-263',
 'TEST RESULTS': 'medical-N-264',
 'DOCTOR VISITS': 'medical-N-265',
 'NOTES': 'medical-N-266',
 'APPOINTMENTS': 'medical-N-267',
 'IMAGING RESULTS': 'medical-N-268',
 'REPORTS': 'medical-N-269',
 'SPECIFIC DISEASE': 'medical-N-270',
 'PAPERS': 'medical-N-271',
 'FILES': 'medical-N-272',
 'INSURANCE FORMS': 'medical-N-273',
 'MEDICAL RECORDS': 'medical-N-274',
 'COMPUTER': 'medical-N-275',
 'LIST OF CONTACT INFORMATION': 'medical-N-276',
 'PHONE': 'medical-N-277',
 'REPORTS ABOUT YOUR SPECIFIC DISEASE': 'medical-N-278',
 'CONTACT INFORMATION': 'medical-N-279',
 'PRIMARY CARE PHYSICIAN': 'medical-N-280',
 'LIST': 'medical-N-281',
 'MEDICAL BINDER': 'medical-N-282',
 'NOTEBOOK': 'medical-N-283',
 'RECORDS': 'medical-N-284',
 'REPORTS ABOUT YOUR SPECIFIC TYPE OF CANCER': 'medical-N-285',
 'SECOND OPINION': 'medical-N-286',
 'BINDER': 'medical-N-287',
 'ZIPPER POCKET': 'medical-N-288',
 'PEN': 'medical-N-289',
 'SMALL CALENDAR': 'medical-N-290',
 'INSURANCE CARDS': 'medical-N-291',
 'FOLDERS': 'medical-N-292',
 'ONLINE PATIENT PORTALS': 'medical-N-293',
 'MEDICAL HISTORY': 'medical-N-294',
 'HEALTH ISSUES': 'medical-N-295',
 'TREATMENTS': 'medical-N-296',
 'ILLNESS': 'medical-N-297',
 'INJURY': 'medical-N-298',
 'OLD MEDICINES': 'medical-N-299',
 'NEW MEDICINES': 'medical-N-300',
 'OVER-THE-COUNTER MEDICINES': 'medical-N-301',
 'HERBALS': 'medical-N-302',
 'SUPPLEMENTS': 'medical-N-303',
 'HEALTH HISTORY': 'medical-N-304',
 'FAMILY HISTORY': 'medical-N-305',
 'CANCERS': 'medical-N-306',
 'DISEASES': 'medical-N-307',
 'FAMILIES': 'medical-N-308',
 'HEALTH HISTORY OF FAMILY MEMBERS WHO ARE BLOOD RELATIVES': 'medical-N-309',
 'HEART DISEASE': 'medical-N-310',
 'DIABETES': 'medical-N-311',
 'AGE OF DIAGNOSIS': 'medical-N-312',
 'OLD AND NEW MEDICINES': 'medical-N-313',
 'MEDICAL OR HEALTH HISTORY': 'medical-N-314',
 'PAIN': 'medical-N-315',
 'ENLARGED LYMPH NODES': 'medical-N-316',
 'UNDERARM': 'medical-N-317',
 'GROIN': 'medical-N-318',
 'LUMPS': 'medical-N-319',
 'HEALTH HISTORY OF FAMILY MEMBERS': 'medical-N-320',
 'BLOOD RELATIVES': 'medical-N-321',
 'NCCN GUIDELINES FOR PATIENTS® ADRENAL TUMORS': 'medical-N-322',
 '2022': 'medical-N-323',
 'FAMILY HEALTH HISTORY': 'medical-N-324',
 'PARENT': 'medical-N-325',
 'RELATIVES WHO HAVE DIED': 'medical-N-326',
 'CAUSE OF DEATH': 'medical-N-327',
 'AGE OF DEATH': 'medical-N-328',
 'PARENTS': 'medical-N-329',
 'SIBLINGS': 'medical-N-330',
 'CHILDREN': 'medical-N-331',
 'HALF-SIBLINGS': 'medical-N-332',
 'AUNTS AND UNCLES': 'medical-N-333',
 'NIECE AND NEPHEWS': 'medical-N-334',
 'GRANDPARENTS': 'medical-N-335',
 'GRANDCHILDREN': 'medical-N-336',
 'CHRONIC DISEASES': 'medical-N-337',
 'HEALTH CONDITIONS': 'medical-N-338',
 'HIGH CHOLESTEROL': 'medical-N-339',
 'STROKE': 'medical-N-340',
 'FAMILY’S ANCESTRY': 'medical-N-341',
 'COUNTRIES': 'medical-N-342',
 'ANCESTORS': 'medical-N-343',
 'PICTURES OF THE INSIDE OF YOUR BODY': 'medical-N-344',
 'RADIOLOGIST': 'medical-N-345',
 'TEST IMAGES': 'medical-N-346',
 'REPORT': 'medical-N-347',
 'COMPUTED TOMOGRAPHY (CT OR CAT) SCAN': 'medical-N-348',
 'X-RAYS': 'medical-N-349',
 'COMPUTER TECHNOLOGY': 'medical-N-350',
 'PICTURES OF THE INSIDE OF THE BODY': 'medical-N-351',
 'BODY PART': 'medical-N-352',
 'IMAGES': 'medical-N-353',
 'THREE-DIMENSIONAL (3D) PICTURE': 'medical-N-354',
 'CONTRAST': 'medical-N-355',
 'CAT SCAN': 'medical-N-356',
 '3D PICTURE': 'medical-N-357',
 'MOUTH (ORAL)': 'medical-N-358',
 'VEIN (IV)': 'medical-N-359',
 'URINE': 'medical-N-360',
 'MRI': 'medical-N-361',
 'ALLERGIC REACTIONS': 'medical-N-362',
 'MEDICINES': 'medical-N-363',
 'DIPHENHYDRAMINE (BENADRYL)': 'medical-N-364',
 'PREDNISONE (STEROIDS)': 'medical-N-365',
 'ALLERGIES': 'medical-N-366',
 'MAGNETIC RESONANCE IMAGING': 'medical-N-367',
 'RADIO WAVES': 'medical-N-368',
 'POWERFUL MAGNETS': 'medical-N-369',
 'INITIAL TEST': 'medical-N-370',
 'TREATMENT RESULTS': 'medical-N-371',
 'OTHER PARTS OF THE BODY': 'medical-N-372',
 'PET SCAN': 'medical-N-373',
 'POSITRON EMISSION TOMOGRAPHY': 'medical-N-374',
 'RADIOACTIVE DRUG': 'medical-N-375',
 'TRACER': 'medical-N-376',
 'VEIN': 'medical-N-377',
 'CANCER CELLS': 'medical-N-378',
 'HOUR': 'medical-N-379',
 'CT SCANS': 'medical-N-380',
 'MRI SCANS': 'medical-N-381',
 'PET/CT': 'medical-N-382',
 'PET/MRI': 'medical-N-383',
 'COMBINED TEST': 'medical-N-384',
 'FDG-PET': 'medical-N-385',
 'SSTR-PET': 'medical-N-386',
 'FDG-PET/CT SCAN': 'medical-N-387',
 'FDG-PET SCAN': 'medical-N-388',
 'RADIOACTIVE TYPE OF SUGAR': 'medical-N-389',
 '18-FLUORODEOXYGLUCOSE': 'medical-N-390',
 'ACTIVE CANCER CELLS': 'medical-N-391',
 'SUGAR': 'medical-N-392',
 'NORMAL CELLS': 'medical-N-393',
 'PICTURES': 'medical-N-394',
 'NEUROENDOCRINE TUMORS': 'medical-N-395',
 'PET SCANS': 'medical-N-396',
 'SSTRPET': 'medical-N-397',
 'SOMATOSTATIN': 'medical-N-398',
 'SSTRS': 'medical-N-399',
 'HORMONE SECRETION': 'medical-N-400',
 'BIOCHEMICAL TESTS': 'medical-N-401',
 'BLOOD': 'medical-N-402',
 'SALIVA': 'medical-N-403',
 'SYNDROMES': 'medical-N-404',
 'GUIDE GUIDE 1 BIOCHEMICAL TESTS': 'medical-N-405',
 'FAIR-SKINNED PEOPLE': 'medical-N-406',
 'BASAL CELL CARCINOMA': 'medical-N-407',
 'NONMELANOMA SKIN CANCERS': 'medical-N-408',
 'KERATINOCYTE CARCINOMAS': 'medical-N-409',
 'BASAL CELL SKIN CANCERS': 'medical-N-410',
 'SQUAMOUS CELL': 'medical-N-411',
 'SQUAMOUS CELL CARCINOMA': 'medical-N-412',
 'TOP LAYER OF THE SKIN': 'medical-N-413',
 'LUNGS': 'medical-N-414',
 'THYROID': 'medical-N-415',
 'ESOPHAGUS': 'medical-N-416',
 'CUTANEOUS SQUAMOUS CELL CARCINOMA': 'medical-N-417',
 'SQUAMOUS CELL SKIN CANCERS': 'medical-N-418',
 'SCALY PATCHES': 'medical-N-419',
 'CUTANEOUS SQUAMOUS CELL CARCINOMA (CSCC)': 'medical-N-420',
 'PATIENT GUIDE': 'medical-N-421',
 'INVADERS': 'medical-N-422',
 'MICROBES': 'medical-N-423',
 'SENSATIONS OF TOUCH': 'medical-N-424',
 'HEAT': 'medical-N-425',
 'COLD': 'medical-N-426',
 'SWEAT GLANDS': 'medical-N-427',
 'HYPODERMIS (SUBCUTIS)': 'medical-N-428',
 'FISH SCALES': 'medical-N-429',
 'TISSUE THAT FORMS THE SURFACE OF THE SKIN': 'medical-N-430',
 'LOWER PART OF THE EPIDERMIS': 'medical-N-431',
 'BASAL CELL LAYER': 'medical-N-432',
 'TOP LAYER OF SKIN': 'medical-N-433',
 'TISSUE': 'medical-N-434',
 'SURFACE OF THE SKIN': 'medical-N-435',
 'SKIN’S SURFACE': 'medical-N-436',
 'COLOR': 'medical-N-437',
 'HARMFUL ULTRAVIOLET (UV) RAYS': 'medical-N-438',
 'RISK FACTOR': 'medical-N-439',
 'DISEASE': 'medical-N-440',
 'SMOKING CIGARETTES': 'medical-N-441',
 'LUNG CANCER': 'medical-N-442',
 'SUNLIGHT/OUTDOOR TANNING': 'medical-N-443',
 'PEOPLE WHO SUNBURN EASILY': 'medical-N-444',
 'PEOPLE WITH LIGHT SKIN, HAIR, AND EYES': 'medical-N-445',
 'PEOPLE WHO WORK OUTDOORS': 'medical-N-446',
 'LONGTERM SUN EXPOSURE': 'medical-N-447',
 'FREQUENT TANNING': 'medical-N-448',
 'SUNBURNS': 'medical-N-449',
 'INDOOR TANNING': 'medical-N-450',
 'MAJOR RISK FACTOR': 'medical-N-451',
 'INDOOR TANNING MACHINES': 'medical-N-452',
 'BOOTHS': 'medical-N-453',
 'BEDS': 'medical-N-454',
 'ANY TYPE OF SKIN CANCER': 'medical-N-455',
 'ENVIRONMENTAL TOXINS': 'medical-N-456',
 'POLLUTANTS': 'medical-N-457',
 'TOBACCO SMOKE': 'medical-N-458',
 'EXHAUST FROM CARS OR OTHER VEHICLES': 'medical-N-459',
 'ARSENIC': 'medical-N-460',
 'SOIL': 'medical-N-461',
 'WATER': 'medical-N-462',
 'AIR': 'medical-N-463',
 'SKIN DAMAGE': 'medical-N-464',
 'SCARS': 'medical-N-465',
 'CHRONIC WOUNDS': 'medical-N-466',
 'ULCERS': 'medical-N-467',
 'SORES': 'medical-N-468',
 'BURNS': 'medical-N-469',
 'MARJOLIN’S ULCER': 'medical-N-470',
 'ACTINIC KERATOSIS': 'medical-N-471',
 'SCALY OR ROUGH SKIN': 'medical-N-472',
 'RED': 'medical-N-473',
 'WHITE': 'medical-N-474',
 'TAN': 'medical-N-475',
 'PINK': 'medical-N-476',
 'SMALL SCALY SPOTS': 'medical-N-477',
 'BUMPS': 'medical-N-478',
 'WARTS': 'medical-N-479',
 'DERMATOLOGIST': 'medical-N-480',
 'ACTINIC KERATOSIS ON THE HAND': 'medical-N-481',
 'ACTINIC KERATOSIS ON TOP OF HEAD': 'medical-N-482',
 'GENETIC SYNDROMES': 'medical-N-483',
 'XERODERMA PIGMENTOSUM': 'medical-N-484',
 'XP': 'medical-N-485',
 'SUNLIGHT': 'medical-N-486',
 'SKIN CELLS': 'medical-N-487',
 'DNA DAMAGE': 'medical-N-488',
 'RECESSIVE DYSTROPHIC EPIDERMOLYSIS BULLOSA': 'medical-N-489',
 'RDEB': 'medical-N-490',
 'RARE, INHERITED SKIN DISORDER': 'medical-N-491',
 'TRAUMA TO THE SKIN': 'medical-N-492',
 'PAINFUL BLISTERS': 'medical-N-493',
 'CANCER CENTER': 'medical-N-494',
 'SQUAMOUS CELL CARCINOMA PREVENTION AND TREATMENT': 'medical-N-495',
 'GENETIC RISK OF SKIN CANCER': 'medical-N-496',
 'CANCER GENETICS': 'medical-N-497',
 'GENETIC COUNSELOR': 'medical-N-498',
 'MEDICAL GENETICIST': 'medical-N-499',
 'ENDOCRINOLOGIST': 'medical-N-500',
 'ONCOLOGIST': 'medical-N-501',
 'SURGEON': 'medical-N-502',
 'ONCOLOGY NURSE': 'medical-N-503',
 'PEOPLE WITH GENETIC SYNDROMES': 'medical-N-504',
 'PEOPLE WITH GENETIC RISK OF SKIN CANCER': 'medical-N-505',
 'WEAKENED IMMUNE SYSTEM': 'medical-N-506',
 'VIRUSES': 'medical-N-507',
 'FUNGI': 'medical-N-508',
 'CSCC PREVENTION': 'medical-N-509',
 'CSCC TREATMENT': 'medical-N-510',
 'COUNSELING': 'medical-N-511',
 'TREATMENT PROCESS': 'medical-N-512',
 'ORGAN TRANSPLANTATION': 'medical-N-513',
 'ORGAN': 'medical-N-514',
 'DRUGS': 'medical-N-515',
 'IMMUNOSUPPRESSANTS': 'medical-N-516',
 'INFECTION': 'medical-N-517',
 'LYMPHOMA': 'medical-N-518',
 'CANCER OF THE LYMPH NODES': 'medical-N-519',
 'CHRONIC LYMPHOCYTIC LEUKEMIA': 'medical-N-520',
 'CANCER OF WHITE BLOOD CELLS IN BONE MARROW': 'medical-N-521',
 'HUMAN IMMUNODEFICIENCY VIRUS (HIV)': 'medical-N-522',
 'AIDS': 'medical-N-523',
 'SKIN CANCER SCREENING': 'medical-N-524',
 'ABNORMAL-LOOKING SKIN': 'medical-N-525',
 'FULL HEALTH HISTORY': 'medical-N-526',
 'EXAMINATION OF THE LESION(S)': 'medical-N-527',
 'SKIN BIOPSY': 'medical-N-528',
 'SAMPLE OF THE LESION': 'medical-N-529',
 'IMAGING SCANS': 'medical-N-530',
 'LAB': 'medical-N-531',
 'MICROSCOPE': 'medical-N-532',
 'SAMPLE': 'medical-N-533',
 'PATHOLOGIST': 'medical-N-534',
 'OVERALL APPEARANCE': 'medical-N-535',
 'SIZE': 'medical-N-536',
 'SHAPE': 'medical-N-537',
 'TYPE OF CELLS': 'medical-N-538',
 'WAYS TO DO A SKIN BIOPSY': 'medical-N-539',
 'SMALL SCAR': 'medical-N-540',
 'DIFFERENT METHODS': 'medical-N-541',
 'DIFFERENT TYPES OF SCARS': 'medical-N-542',
 'TYPE OF BIOPSY': 'medical-N-543',
 'RISK OF SCARRING': 'medical-N-544',
 'SUSPECTED AREA': 'medical-N-545',
 'ACCURATE DIAGNOSIS': 'medical-N-546',
 'LOCAL ANESTHETIC': 'medical-N-547',
 'NUMBING MEDICINE': 'medical-N-548',
 'AREA': 'medical-N-549',

In [12]:
total_edges = sum(len(node.edges) for node in medical_nodes.values())//2
print("Total edges:", total_edges)

Total edges: 101343

In [13]:
#data for visualization using Gephi
import networkx as nx
G = nx.Graph()
for node_id, node in medical_nodes.items():
    G.add_node(node_id, node_type=node.node_type, content=node.content, source=node.source)
    for target_id, weight in node.edges.items():
        if target_id in medical_nodes:
            G.add_edge(node_id, target_id, weight=weight)

nx.write_gml(G, "viz/medical_graph.gml")